; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	number_zero:BYTE:038H
COMM	hLocalHeap:QWORD
_DATA	ENDS
PUBLIC	AllocateHeapArea
PUBLIC	DeallocateHeapArea
PUBLIC	AllocateBlock
PUBLIC	DeallocateBlock
PUBLIC	CheckBlockLight
PUBLIC	AttatchNumber
PUBLIC	AllocateNumber
PUBLIC	DetatchNumber
PUBLIC	DeallocateNumber
PUBLIC	CommitNumber
PUBLIC	CheckNumber
PUBLIC	DuplicateNumber
PUBLIC	Initialize_Memory
PUBLIC	PMC_Dispose
EXTRN	__imp_HeapCreate:PROC
EXTRN	__imp_HeapDestroy:PROC
EXTRN	__imp_HeapAlloc:PROC
EXTRN	__imp_HeapFree:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$AllocateHeapArea DD imagerel $LN5
	DD	imagerel $LN5+42
	DD	imagerel $unwind$AllocateHeapArea
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$DeallocateHeapArea DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$DeallocateHeapArea
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$AllocateBlock DD imagerel $LN8
	DD	imagerel $LN8+128
	DD	imagerel $unwind$AllocateBlock
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$DeallocateBlock DD imagerel $LN9
	DD	imagerel $LN9+23
	DD	imagerel $unwind$DeallocateBlock
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$DeallocateBlock DD imagerel $LN9+23
	DD	imagerel $LN9+69
	DD	imagerel $chain$0$DeallocateBlock
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$DeallocateBlock DD imagerel $LN9+69
	DD	imagerel $LN9+79
	DD	imagerel $chain$1$DeallocateBlock
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$AttatchNumber DD imagerel $LN5
	DD	imagerel $LN5+31
	DD	imagerel $unwind$AttatchNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$AllocateNumber DD imagerel $LN6
	DD	imagerel $LN6+110
	DD	imagerel $unwind$AllocateNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$DeallocateNumber DD imagerel $LN27
	DD	imagerel $LN27+85
	DD	imagerel $unwind$DeallocateNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CommitNumber DD imagerel $LN39
	DD	imagerel $LN39+346
	DD	imagerel $unwind$CommitNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$DuplicateNumber DD imagerel $LN18
	DD	imagerel $LN18+194
	DD	imagerel $unwind$DuplicateNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$Initialize_Memory DD imagerel $LN47
	DD	imagerel $LN47+81
	DD	imagerel $unwind$Initialize_Memory
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_Dispose DD imagerel $LN32
	DD	imagerel $LN32+85
	DD	imagerel $unwind$PMC_Dispose
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_COPY_MEMORY_UNIT DD imagerel _COPY_MEMORY_UNIT
	DD	imagerel _COPY_MEMORY_UNIT+33
	DD	imagerel $unwind$_COPY_MEMORY_UNIT
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_ZERO_MEMORY_BYTE DD imagerel _ZERO_MEMORY_BYTE
	DD	imagerel _ZERO_MEMORY_BYTE+21
	DD	imagerel $unwind$_ZERO_MEMORY_BYTE
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_ZERO_MEMORY_16 DD imagerel _ZERO_MEMORY_16
	DD	imagerel _ZERO_MEMORY_16+22
	DD	imagerel $unwind$_ZERO_MEMORY_16
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_ZERO_MEMORY_32 DD imagerel _ZERO_MEMORY_32
	DD	imagerel _ZERO_MEMORY_32+21
	DD	imagerel $unwind$_ZERO_MEMORY_32
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_ZERO_MEMORY_64 DD imagerel _ZERO_MEMORY_64
	DD	imagerel _ZERO_MEMORY_64+22
	DD	imagerel $unwind$_ZERO_MEMORY_64
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_FILL_MEMORY_BYTE DD imagerel _FILL_MEMORY_BYTE
	DD	imagerel _FILL_MEMORY_BYTE+22
	DD	imagerel $unwind$_FILL_MEMORY_BYTE
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_FILL_MEMORY_16 DD imagerel _FILL_MEMORY_16
	DD	imagerel _FILL_MEMORY_16+23
	DD	imagerel $unwind$_FILL_MEMORY_16
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_FILL_MEMORY_32 DD imagerel _FILL_MEMORY_32
	DD	imagerel _FILL_MEMORY_32+21
	DD	imagerel $unwind$_FILL_MEMORY_32
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_FILL_MEMORY_64 DD imagerel _FILL_MEMORY_64
	DD	imagerel _FILL_MEMORY_64+23
	DD	imagerel $unwind$_FILL_MEMORY_64
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_FILL_MEMORY_UNIT DD imagerel _FILL_MEMORY_UNIT
	DD	imagerel _FILL_MEMORY_UNIT+23
	DD	imagerel $unwind$_FILL_MEMORY_UNIT
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$InitializeNumber DD imagerel InitializeNumber
	DD	imagerel InitializeNumber+191
	DD	imagerel $unwind$InitializeNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CleanUpNumber DD imagerel CleanUpNumber
	DD	imagerel CleanUpNumber+35
	DD	imagerel $unwind$CleanUpNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$CleanUpNumber DD imagerel CleanUpNumber+35
	DD	imagerel CleanUpNumber+76
	DD	imagerel $chain$0$CleanUpNumber
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$CleanUpNumber DD imagerel CleanUpNumber+76
	DD	imagerel CleanUpNumber+90
	DD	imagerel $chain$1$CleanUpNumber
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$CleanUpNumber DD 021H
	DD	imagerel CleanUpNumber
	DD	imagerel CleanUpNumber+35
	DD	imagerel $unwind$CleanUpNumber
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$CleanUpNumber DD 020521H
	DD	067405H
	DD	imagerel CleanUpNumber
	DD	imagerel CleanUpNumber+35
	DD	imagerel $unwind$CleanUpNumber
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CleanUpNumber DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$InitializeNumber DD 0a1a01H
	DD	09741aH
	DD	08641aH
	DD	07541aH
	DD	06341aH
	DD	0e016321aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_FILL_MEMORY_UNIT DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_FILL_MEMORY_64 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_FILL_MEMORY_32 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_FILL_MEMORY_16 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_FILL_MEMORY_BYTE DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_ZERO_MEMORY_64 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_ZERO_MEMORY_32 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_ZERO_MEMORY_16 DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_ZERO_MEMORY_BYTE DD 020501H
	DD	017405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_COPY_MEMORY_UNIT DD 040a01H
	DD	02740aH
	DD	016405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_Dispose DD 020a01H
	DD	03006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$Initialize_Memory DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DuplicateNumber DD 085401H
	DD	077454H
	DD	06344fH
	DD	08640bH
	DD	0e007320bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CommitNumber DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DeallocateNumber DD 020a01H
	DD	03006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$AllocateNumber DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$AttatchNumber DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$DeallocateBlock DD 021H
	DD	imagerel $LN9
	DD	imagerel $LN9+23
	DD	imagerel $unwind$DeallocateBlock
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$DeallocateBlock DD 020521H
	DD	047405H
	DD	imagerel $LN9
	DD	imagerel $LN9+23
	DD	imagerel $unwind$DeallocateBlock
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DeallocateBlock DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$AllocateBlock DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DeallocateHeapArea DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$AllocateHeapArea DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT GetTrailingZeroBitCount
_TEXT	SEGMENT
p$ = 8
word_count$ = 16
GetTrailingZeroBitCount PROC				; COMDAT

; 450  :     __UNIT_TYPE bit_count = 0;

	xor	r8d, r8d

; 451  :     while (word_count > 0)

	test	rdx, rdx
	je	SHORT $LN3@GetTrailin
	npad	8
$LL2@GetTrailin:

; 452  :     {
; 453  :         --word_count;
; 454  :         if (*p != 0)

	mov	rax, QWORD PTR [rcx]
	dec	rdx
	test	rax, rax
	jne	SHORT $LN10@GetTrailin

; 456  :         bit_count += __UNIT_TYPE_BIT_COUNT;

	add	r8, 64					; 00000040H

; 457  :         ++p;

	add	rcx, 8
	test	rdx, rdx
	jne	SHORT $LL2@GetTrailin
$LN3@GetTrailin:

; 458  :     }
; 459  :     // このルートには到達しないはず
; 460  :     return (0);

	xor	eax, eax

; 461  : }

	ret	0
$LN10@GetTrailin:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 984  :     _BitScanForward64(&pos, x);

	bsf	rax, rax
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 455  :             return (bit_count + _TZCNT_ALT_UNIT(*p));

	add	rax, r8

; 461  : }

	ret	0
GetTrailingZeroBitCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT GetEffectiveBitLength
_TEXT	SEGMENT
p$ = 8
word_count$ = 16
effective_word_count$ = 24
GetEffectiveBitLength PROC				; COMDAT

; 428  :     if (p == NULL)

	test	rcx, rcx
	je	SHORT $LN3@GetEffecti

; 429  :     {
; 430  :         *effective_word_count = 0;
; 431  :         return (0);
; 432  :     }
; 433  :     p += word_count;

	lea	rax, QWORD PTR [rcx+rdx*8]

; 434  :     while (word_count != 0)

	test	rdx, rdx
	je	SHORT $LN3@GetEffecti
	npad	2
$LL2@GetEffecti:

; 435  :     {
; 436  :         --p;
; 437  :         if (*p != 0)

	cmp	QWORD PTR [rax-8], 0
	lea	rax, QWORD PTR [rax-8]
	jne	SHORT $LN11@GetEffecti

; 441  :         }
; 442  :         --word_count;

	sub	rdx, 1
	jne	SHORT $LL2@GetEffecti
$LN3@GetEffecti:

; 443  :     }
; 444  :     *effective_word_count = 0;

	mov	QWORD PTR [r8], 0

; 445  :     return (0);

	xor	eax, eax

; 446  : }

	ret	0
$LN11@GetEffecti:

; 438  :         {
; 439  :             *effective_word_count = word_count;

	mov	QWORD PTR [r8], rdx

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	mov	rcx, QWORD PTR [rax]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 890  :     if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN8@GetEffecti

; 891  :         return (sizeof(x) * 8);

	mov	eax, 64					; 00000040H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	shl	rdx, 6
	sub	rdx, rax
	mov	rax, rdx

; 446  : }

	ret	0
$LN8@GetEffecti:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 904  :     _BitScanReverse64(&pos, x);

	bsr	rcx, rcx

; 914  :     return (sizeof(x) * 8 - 1 - pos);

	mov	eax, 63					; 0000003fH
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	shl	rdx, 6
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 914  :     return (sizeof(x) * 8 - 1 - pos);

	sub	rax, rcx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	sub	rdx, rax
	mov	rax, rdx

; 446  : }

	ret	0
GetEffectiveBitLength ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CleanUpNumber
_TEXT	SEGMENT
p$ = 48
CleanUpNumber PROC					; COMDAT

; 380  : {

	push	rbx
	sub	rsp, 32					; 00000020H

; 381  :     if (p->BLOCK != NULL)

	mov	rax, QWORD PTR [rcx+48]
	mov	rbx, rcx
	test	rax, rax
	je	SHORT $LN2@CleanUpNum

; 382  :     {
; 383  :         DeallocateBlock(p->BLOCK, p->BLOCK_COUNT);

	mov	rcx, QWORD PTR [rcx+40]

; 205  :         __UNIT_TYPE* p = buffer - 1;

	lea	r8, QWORD PTR [rax-8]

; 206  :         if (*p != buffer_words)

	cmp	QWORD PTR [r8], rcx
	jne	SHORT $LN7@CleanUpNum

; 207  :         {
; 208  :             // もし、buffer の指す内容が壊れていることが明らかならば、二重解放の恐れがあるので解放処理はしない。
; 209  :         }
; 210  :         else
; 211  :         {
; 212  :             // 使用済みのバッファを既定のデータで塗りつぶす。
; 213  :             _FILL_MEMORY_UNIT(p, DEFAULT_MEMORY_DATA, buffer_words + 2);

	add	rcx, 2
	mov	QWORD PTR [rsp+48], rdi
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 430  :     __stosq(d, x, count);

	mov	rdi, r8
	mov	rax, -3689348814741910324		; ccccccccccccccccH
	rep stosq
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 215  :             HeapFree(hLocalHeap, 0, p);

	mov	rcx, QWORD PTR hLocalHeap
	xor	edx, edx
	call	QWORD PTR __imp_HeapFree
	mov	rdi, QWORD PTR [rsp+48]
$LN7@CleanUpNum:

; 384  :         p->BLOCK = NULL;

	mov	QWORD PTR [rbx+48], 0
$LN2@CleanUpNum:

; 385  :     }
; 386  : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
CleanUpNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT InitializeNumber
_TEXT	SEGMENT
p$ = 48
bit_count$ = 56
light_check_code$ = 64
InitializeNumber PROC					; COMDAT

; 357  : {

	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	mov	QWORD PTR [rsp+32], rdi
	push	r14
	sub	rsp, 32					; 00000020H

; 280  :         __p[0] = 0;

	xor	ebx, ebx

; 357  : {

	mov	r14, r8

; 280  :         __p[0] = 0;

	mov	QWORD PTR [rcx], rbx

; 357  : {

	mov	rbp, rdx

; 281  :         __p[1] = 0;

	mov	QWORD PTR [rcx+8], rbx

; 357  : {

	mov	rdi, rcx

; 282  :         __p[2] = 0;

	mov	QWORD PTR [rcx+16], rbx

; 283  :         __p[3] = 0;

	mov	QWORD PTR [rcx+24], rbx

; 284  :         __p[4] = 0;

	mov	QWORD PTR [rcx+32], rbx

; 285  :         __p[5] = 0;

	mov	QWORD PTR [rcx+40], rbx

; 286  :         __p[6] = 0;

	mov	QWORD PTR [rcx+48], rbx

; 358  :     ClearNumberHeader(p);
; 359  :     if (bit_count > 0)

	test	rdx, rdx
	je	SHORT $LN2@Initialize

; 168  : 	__UNIT_TYPE* buffer = (__UNIT_TYPE*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, bytes);

	mov	rcx, QWORD PTR hLocalHeap
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 454  :     return ((u + v - 1) / v);

	lea	rsi, QWORD PTR [rdx+63]
	shr	rsi, 6
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 168  : 	__UNIT_TYPE* buffer = (__UNIT_TYPE*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, bytes);

	lea	edx, QWORD PTR [rbx+8]
	lea	r8, QWORD PTR [rsi*8+16]
	call	QWORD PTR __imp_HeapAlloc

; 169  : 	if (buffer == NULL)

	test	rax, rax
	je	SHORT $LN32@Initialize

; 170  : 		return (NULL);
; 171  : 	buffer[0] = words1;

	mov	QWORD PTR [rax], rsi

; 172  :     *allocated_block_words = words1;
; 173  : #ifdef _DEBUG
; 174  :     // 乱数もどきを生成する。
; 175  : #ifdef _M_IX86
; 176  :     __UNIT_TYPE r = GetTickCount();
; 177  : #elif defined(_M_IX64)
; 178  : #ifdef _MSC_VER
; 179  :     __UNIT_TYPE r = GetTickCount64();
; 180  : #elif defined(__GNUC__)
; 181  :     _UINT32_T temp = GetTickCount();
; 182  :     __UNIT_TYPE r = _FROMWORDTODWORD(temp, temp);
; 183  : #else
; 184  : #error unknown compiler
; 185  : #endif
; 186  : #else
; 187  : #error unknown platform
; 188  : #endif
; 189  :     __UNIT_TYPE check_code = configuration_info.MEMORY_VERIFICATION_ENABLED ? CalculateCheckCode(&buffer[1], words1) : CHECK_CODE_INIT | r;
; 190  : #else
; 191  :     __UNIT_TYPE check_code = 0;
; 192  : #endif
; 193  :     buffer[words1 + 1] = check_code ^ (__UNIT_TYPE)&buffer[words1 + 1];

	lea	rcx, QWORD PTR [rsi+1]
	lea	rcx, QWORD PTR [rax+rcx*8]
	mov	QWORD PTR [rcx], rcx

; 194  :     if (code != NULL)

	test	r14, r14
	je	SHORT $LN28@Initialize

; 195  :         *code = check_code;

	mov	QWORD PTR [r14], rbx
$LN28@Initialize:

; 196  :     return (&buffer[1]);

	lea	rbx, QWORD PTR [rax+8]

; 360  :     {
; 361  :         __UNIT_TYPE word_count;
; 362  :         __UNIT_TYPE* block = AllocateBlock(bit_count, &word_count, light_check_code);
; 363  :         if (block == NULL)

	test	rbx, rbx
	jne	SHORT $LN3@Initialize
$LN32@Initialize:

; 364  :             return (PMC_STATUS_NOT_ENOUGH_MEMORY);

	mov	eax, -5
	jmp	SHORT $LN1@Initialize
$LN2@Initialize:

; 365  :         p->UNIT_BIT_COUNT = bit_count;
; 366  :         p->BLOCK_COUNT = word_count;
; 367  :         p->BLOCK = block;
; 368  :     }
; 369  :     else
; 370  :     {
; 371  :         // bit_count に 0 が与えられるのは、数値が 0 の場合。
; 372  :         p->UNIT_BIT_COUNT = 0;
; 373  :         p->BLOCK_COUNT = 0;
; 374  :         p->BLOCK = NULL;

	mov	rsi, rbx
	mov	rbp, rbx
$LN3@Initialize:

; 375  :     }
; 376  :     return (PMC_STATUS_OK);

	mov	QWORD PTR [rdi+8], rbp
	xor	eax, eax
	mov	QWORD PTR [rdi+40], rsi
	mov	QWORD PTR [rdi+48], rbx
$LN1@Initialize:

; 377  : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	mov	rdi, QWORD PTR [rsp+72]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
InitializeNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT FillNumberHeader
_TEXT	SEGMENT
p$ = 8
FillNumberHeader PROC					; COMDAT

; 317  : #ifdef _M_IX64
; 318  :     if (sizeof(*p) == sizeof(_UINT64_T) * 7)
; 319  :     {
; 320  :         _UINT64_T* __p = (_UINT64_T*)p;
; 321  :         __p[0] = DEFAULT_MEMORY_DATA;

	mov	rax, -3689348814741910324		; ccccccccccccccccH
	mov	QWORD PTR [rcx], rax

; 322  :         __p[1] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+8], rax

; 323  :         __p[2] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+16], rax

; 324  :         __p[3] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+24], rax

; 325  :         __p[4] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+32], rax

; 326  :         __p[5] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+40], rax

; 327  :         __p[6] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rcx+48], rax

; 328  :     }
; 329  :     else if (sizeof(*p) % sizeof(_UINT64_T) == 0)
; 330  :         _FILL_MEMORY_64((_UINT64_T*)p, DEFAULT_MEMORY_DATA, sizeof(*p) / sizeof(_UINT64_T));
; 331  :     else
; 332  :     {
; 333  : #endif
; 334  :         if (sizeof(*p) == sizeof(_UINT32_T) * 7)
; 335  :         {
; 336  :             _UINT32_T* __p = (_UINT32_T*)p;
; 337  :             __p[0] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 338  :             __p[1] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 339  :             __p[2] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 340  :             __p[3] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 341  :             __p[4] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 342  :             __p[5] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 343  :             __p[6] = (_UINT32_T)DEFAULT_MEMORY_DATA;
; 344  :         }
; 345  :         else if (sizeof(*p) % sizeof(_UINT32_T) == 0)
; 346  :             _FILL_MEMORY_32((_UINT32_T*)p, (_UINT32_T)DEFAULT_MEMORY_DATA, sizeof(*p) / sizeof(_UINT32_T));
; 347  :         else if (sizeof(*p) % sizeof(_UINT16_T) == 0)
; 348  :             _FILL_MEMORY_16((_UINT16_T*)p, (_UINT16_T)DEFAULT_MEMORY_DATA, sizeof(*p) / sizeof(_UINT16_T));
; 349  :         else
; 350  :             _FILL_MEMORY_BYTE(p, (unsigned char)DEFAULT_MEMORY_DATA, sizeof(*p));
; 351  : #ifdef _M_IX64
; 352  :     }
; 353  : #endif
; 354  : }

	ret	0
FillNumberHeader ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT ClearNumberHeader
_TEXT	SEGMENT
p$ = 8
ClearNumberHeader PROC					; COMDAT

; 276  : #ifdef _M_IX64
; 277  :     if (sizeof(*p) == sizeof(_UINT64_T) * 7)
; 278  :     {
; 279  :         _UINT64_T* __p = (_UINT64_T*)p;
; 280  :         __p[0] = 0;

	xor	eax, eax
	mov	QWORD PTR [rcx], rax

; 281  :         __p[1] = 0;

	mov	QWORD PTR [rcx+8], rax

; 282  :         __p[2] = 0;

	mov	QWORD PTR [rcx+16], rax

; 283  :         __p[3] = 0;

	mov	QWORD PTR [rcx+24], rax

; 284  :         __p[4] = 0;

	mov	QWORD PTR [rcx+32], rax

; 285  :         __p[5] = 0;

	mov	QWORD PTR [rcx+40], rax

; 286  :         __p[6] = 0;

	mov	QWORD PTR [rcx+48], rax

; 287  :     }
; 288  :     else if (sizeof(*p) % sizeof(_UINT64_T) == 0)
; 289  :         _ZERO_MEMORY_64((_UINT64_T*)p, sizeof(*p) / sizeof(_UINT64_T));
; 290  :     else
; 291  :     {
; 292  : #endif
; 293  :         if (sizeof(*p) == sizeof(_UINT32_T) * 7)
; 294  :         {
; 295  :             _UINT32_T* __p = (_UINT32_T*)p;
; 296  :             __p[0] = 0;
; 297  :             __p[1] = 0;
; 298  :             __p[2] = 0;
; 299  :             __p[3] = 0;
; 300  :             __p[4] = 0;
; 301  :             __p[5] = 0;
; 302  :             __p[6] = 0;
; 303  :         }
; 304  :         else if (sizeof(*p) % sizeof(_UINT32_T) == 0)
; 305  :             _ZERO_MEMORY_32((_UINT32_T*)p, sizeof(*p) / sizeof(_UINT32_T));
; 306  :         else if (sizeof(*p) % sizeof(_UINT16_T) == 0)
; 307  :             _ZERO_MEMORY_16((_UINT16_T*)p, sizeof(*p) / sizeof(_UINT16_T));
; 308  :         else
; 309  :             _ZERO_MEMORY_BYTE(p, sizeof(*p));
; 310  : #ifdef _M_IX64
; 311  :     }
; 312  : #endif
; 313  : }

	ret	0
ClearNumberHeader ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CommitBlock
_TEXT	SEGMENT
buffer$ = 8
CommitBlock PROC					; COMDAT

; 223  :     if (buffer != NULL)

	test	rcx, rcx
	je	SHORT $LN2@CommitBloc

; 224  :     {
; 225  :         --buffer;
; 226  :         __UNIT_TYPE words = buffer[0];
; 227  : #ifdef _DEBUG
; 228  :         __UNIT_TYPE code = CalculateCheckCode(&buffer[1], words);
; 229  : #else
; 230  :         __UNIT_TYPE code = 0;
; 231  : #endif
; 232  :         buffer[words + 1] = code;

	mov	rax, QWORD PTR [rcx-8]
	mov	QWORD PTR [rcx+rax*8], 0
$LN2@CommitBloc:

; 233  :     }
; 234  : }

	ret	0
CommitBlock ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CalculateCheckCode
_TEXT	SEGMENT
p$ = 8
words$ = 16
CalculateCheckCode PROC					; COMDAT

; 58   : 	__UNIT_TYPE code = CHECK_CODE_INIT;
; 59   : 	
; 60   :     __UNIT_TYPE count = words >> 5;

	mov	r8, rdx
	mov	rax, -8897841259083430780		; 8484848484848484H
	shr	r8, 5

; 61   : 	while (count != 0)

	test	r8, r8
	je	$LN3@CalculateC
	npad	6
$LL2@CalculateC:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 63   :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 64   :         code = _ROTATE_L_UNIT(code, 3) ^ p[1];

	xor	rax, QWORD PTR [rcx+8]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 65   :         code = _ROTATE_L_UNIT(code, 3) ^ p[2];

	xor	rax, QWORD PTR [rcx+16]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 66   :         code = _ROTATE_L_UNIT(code, 3) ^ p[3];

	xor	rax, QWORD PTR [rcx+24]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 67   :         code = _ROTATE_L_UNIT(code, 3) ^ p[4];

	xor	rax, QWORD PTR [rcx+32]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 68   :         code = _ROTATE_L_UNIT(code, 3) ^ p[5];

	xor	rax, QWORD PTR [rcx+40]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 69   :         code = _ROTATE_L_UNIT(code, 3) ^ p[6];

	xor	rax, QWORD PTR [rcx+48]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 70   :         code = _ROTATE_L_UNIT(code, 3) ^ p[7];

	xor	rax, QWORD PTR [rcx+56]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 71   :         code = _ROTATE_L_UNIT(code, 3) ^ p[8];

	xor	rax, QWORD PTR [rcx+64]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 72   :         code = _ROTATE_L_UNIT(code, 3) ^ p[9];

	xor	rax, QWORD PTR [rcx+72]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 73   :         code = _ROTATE_L_UNIT(code, 3) ^ p[10];

	xor	rax, QWORD PTR [rcx+80]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 74   :         code = _ROTATE_L_UNIT(code, 3) ^ p[11];

	xor	rax, QWORD PTR [rcx+88]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 75   :         code = _ROTATE_L_UNIT(code, 3) ^ p[12];

	xor	rax, QWORD PTR [rcx+96]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 76   :         code = _ROTATE_L_UNIT(code, 3) ^ p[13];

	xor	rax, QWORD PTR [rcx+104]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 77   :         code = _ROTATE_L_UNIT(code, 3) ^ p[14];

	xor	rax, QWORD PTR [rcx+112]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 78   :         code = _ROTATE_L_UNIT(code, 3) ^ p[15];

	xor	rax, QWORD PTR [rcx+120]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 79   :         code = _ROTATE_L_UNIT(code, 3) ^ p[16];

	xor	rax, QWORD PTR [rcx+128]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 80   :         code = _ROTATE_L_UNIT(code, 3) ^ p[17];

	xor	rax, QWORD PTR [rcx+136]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 81   :         code = _ROTATE_L_UNIT(code, 3) ^ p[18];

	xor	rax, QWORD PTR [rcx+144]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 82   :         code = _ROTATE_L_UNIT(code, 3) ^ p[19];

	xor	rax, QWORD PTR [rcx+152]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 83   :         code = _ROTATE_L_UNIT(code, 3) ^ p[20];

	xor	rax, QWORD PTR [rcx+160]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 84   :         code = _ROTATE_L_UNIT(code, 3) ^ p[21];

	xor	rax, QWORD PTR [rcx+168]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 85   :         code = _ROTATE_L_UNIT(code, 3) ^ p[22];

	xor	rax, QWORD PTR [rcx+176]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 86   :         code = _ROTATE_L_UNIT(code, 3) ^ p[23];

	xor	rax, QWORD PTR [rcx+184]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 87   :         code = _ROTATE_L_UNIT(code, 3) ^ p[24];

	xor	rax, QWORD PTR [rcx+192]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 88   :         code = _ROTATE_L_UNIT(code, 3) ^ p[25];

	xor	rax, QWORD PTR [rcx+200]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 89   :         code = _ROTATE_L_UNIT(code, 3) ^ p[26];

	xor	rax, QWORD PTR [rcx+208]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 90   :         code = _ROTATE_L_UNIT(code, 3) ^ p[27];

	xor	rax, QWORD PTR [rcx+216]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 91   :         code = _ROTATE_L_UNIT(code, 3) ^ p[28];

	xor	rax, QWORD PTR [rcx+224]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 92   :         code = _ROTATE_L_UNIT(code, 3) ^ p[29];

	xor	rax, QWORD PTR [rcx+232]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 93   :         code = _ROTATE_L_UNIT(code, 3) ^ p[30];

	xor	rax, QWORD PTR [rcx+240]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 94   :         code = _ROTATE_L_UNIT(code, 3) ^ p[31];

	xor	rax, QWORD PTR [rcx+248]

; 95   :         p += 32;

	add	rcx, 256				; 00000100H

; 96   :         --count;

	sub	r8, 1
	jne	$LL2@CalculateC
$LN3@CalculateC:

; 97   :     }
; 98   : 
; 99   : 	if (words & 0x10)

	test	dl, 16
	je	$LN4@CalculateC
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 101  :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 102  :         code = _ROTATE_L_UNIT(code, 3) ^ p[1];

	xor	rax, QWORD PTR [rcx+8]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 103  :         code = _ROTATE_L_UNIT(code, 3) ^ p[2];

	xor	rax, QWORD PTR [rcx+16]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 104  :         code = _ROTATE_L_UNIT(code, 3) ^ p[3];

	xor	rax, QWORD PTR [rcx+24]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 105  :         code = _ROTATE_L_UNIT(code, 3) ^ p[4];

	xor	rax, QWORD PTR [rcx+32]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 106  :         code = _ROTATE_L_UNIT(code, 3) ^ p[5];

	xor	rax, QWORD PTR [rcx+40]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 107  :         code = _ROTATE_L_UNIT(code, 3) ^ p[6];

	xor	rax, QWORD PTR [rcx+48]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 108  :         code = _ROTATE_L_UNIT(code, 3) ^ p[7];

	xor	rax, QWORD PTR [rcx+56]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 109  :         code = _ROTATE_L_UNIT(code, 3) ^ p[8];

	xor	rax, QWORD PTR [rcx+64]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 110  :         code = _ROTATE_L_UNIT(code, 3) ^ p[9];

	xor	rax, QWORD PTR [rcx+72]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 111  :         code = _ROTATE_L_UNIT(code, 3) ^ p[10];

	xor	rax, QWORD PTR [rcx+80]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 112  :         code = _ROTATE_L_UNIT(code, 3) ^ p[11];

	xor	rax, QWORD PTR [rcx+88]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 113  :         code = _ROTATE_L_UNIT(code, 3) ^ p[12];

	xor	rax, QWORD PTR [rcx+96]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 114  :         code = _ROTATE_L_UNIT(code, 3) ^ p[13];

	xor	rax, QWORD PTR [rcx+104]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 115  :         code = _ROTATE_L_UNIT(code, 3) ^ p[14];

	xor	rax, QWORD PTR [rcx+112]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 116  :         code = _ROTATE_L_UNIT(code, 3) ^ p[15];

	xor	rax, QWORD PTR [rcx+120]

; 117  :         p += 16;

	sub	rcx, -128				; ffffffffffffff80H
$LN4@CalculateC:

; 118  :     }
; 119  : 
; 120  :     if (words & 0x8)

	test	dl, 8
	je	SHORT $LN5@CalculateC
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 122  :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 123  :         code = _ROTATE_L_UNIT(code, 3) ^ p[1];

	xor	rax, QWORD PTR [rcx+8]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 124  :         code = _ROTATE_L_UNIT(code, 3) ^ p[2];

	xor	rax, QWORD PTR [rcx+16]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 125  :         code = _ROTATE_L_UNIT(code, 3) ^ p[3];

	xor	rax, QWORD PTR [rcx+24]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 126  :         code = _ROTATE_L_UNIT(code, 3) ^ p[4];

	xor	rax, QWORD PTR [rcx+32]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 127  :         code = _ROTATE_L_UNIT(code, 3) ^ p[5];

	xor	rax, QWORD PTR [rcx+40]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 128  :         code = _ROTATE_L_UNIT(code, 3) ^ p[6];

	xor	rax, QWORD PTR [rcx+48]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 129  :         code = _ROTATE_L_UNIT(code, 3) ^ p[7];

	xor	rax, QWORD PTR [rcx+56]

; 130  :         p += 8;

	add	rcx, 64					; 00000040H
$LN5@CalculateC:

; 131  :     }
; 132  : 
; 133  :     if (words & 0x4)

	test	dl, 4
	je	SHORT $LN6@CalculateC
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 135  :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 136  :         code = _ROTATE_L_UNIT(code, 3) ^ p[1];

	xor	rax, QWORD PTR [rcx+8]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 137  :         code = _ROTATE_L_UNIT(code, 3) ^ p[2];

	xor	rax, QWORD PTR [rcx+16]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 138  :         code = _ROTATE_L_UNIT(code, 3) ^ p[3];

	xor	rax, QWORD PTR [rcx+24]

; 139  :         p += 4;

	add	rcx, 32					; 00000020H
$LN6@CalculateC:

; 140  :     }
; 141  : 
; 142  :     if (words & 0x2)

	test	dl, 2
	je	SHORT $LN7@CalculateC
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 144  :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 145  :         code = _ROTATE_L_UNIT(code, 3) ^ p[1];

	xor	rax, QWORD PTR [rcx+8]

; 146  :         p += 2;

	add	rcx, 16
$LN7@CalculateC:

; 147  :     }
; 148  : 
; 149  :     if (words & 0x1)

	test	dl, 1
	je	SHORT $LN140@CalculateC
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 745  :     return (_rotl64(x, count));

	rol	rax, 3
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 150  :         code = _ROTATE_L_UNIT(code, 3) ^ p[0];

	xor	rax, QWORD PTR [rcx]
$LN140@CalculateC:

; 151  :     
; 152  :     return (code);
; 153  : }

	ret	0
CalculateCheckCode ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _TZCNT_ALT_UNIT
_TEXT	SEGMENT
x$ = 8
_TZCNT_ALT_UNIT PROC					; COMDAT

; 970  :     if (x == 0)
; 971  :         return (sizeof(x) * 8);

	mov	eax, 64					; 00000040H
	test	rcx, rcx
	je	SHORT $LN1@TZCNT_ALT_

; 972  : #ifdef _M_IX86
; 973  :     _UINT32_T pos;
; 974  : #ifdef _MSC_VER
; 975  :     _BitScanForward(&pos, x);
; 976  : #elif defined(__GNUC__)
; 977  :     __asm__("bsfl %1, %0" : "=r"(pos) : "rm"(x));
; 978  : #else
; 979  : #error unknown compiler
; 980  : #endif
; 981  : #elif defined(_M_X64)
; 982  : #ifdef _MSC_VER
; 983  :     _UINT32_T pos;
; 984  :     _BitScanForward64(&pos, x);

	bsf	rax, rcx
$LN1@TZCNT_ALT_:

; 985  : #elif defined(__GNUC__)
; 986  :     _UINT64_T pos;
; 987  :     __asm__("bsfq %1, %0" : "=r"(pos) : "rm"(x));
; 988  : #else
; 989  : #error unknown compiler
; 990  : #endif
; 991  : #else
; 992  : #error unknown platform
; 993  : #endif
; 994  :     return (pos);
; 995  : }

	ret	0
_TZCNT_ALT_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _LZCNT_ALT_UNIT
_TEXT	SEGMENT
x$ = 8
_LZCNT_ALT_UNIT PROC					; COMDAT

; 890  :     if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN2@LZCNT_ALT_

; 891  :         return (sizeof(x) * 8);

	mov	eax, 64					; 00000040H

; 915  : }

	ret	0
$LN2@LZCNT_ALT_:

; 892  : #ifdef _M_IX86
; 893  :     _UINT32_T pos;
; 894  : #ifdef _MSC_VER
; 895  :     _BitScanReverse(&pos, x);
; 896  : #elif defined(__GNUC__)
; 897  :     __asm__("bsrl %1, %0" : "=r"(pos) : "rm"(x));
; 898  : #else
; 899  : #error unknown compiler
; 900  : #endif
; 901  : #elif defined(_M_X64)
; 902  : #ifdef _MSC_VER
; 903  :     _UINT32_T pos;
; 904  :     _BitScanReverse64(&pos, x);

	bsr	rcx, rcx

; 905  : #elif defined(__GNUC__)
; 906  :     _UINT64_T pos;
; 907  :     __asm__("bsrq %1, %0" : "=r"(pos) : "rm"(x));
; 908  : #else
; 909  : #error unknown compiler
; 910  : #endif
; 911  : #else
; 912  : #error unknown platform
; 913  : #endif
; 914  :     return (sizeof(x) * 8 - 1 - pos);

	mov	eax, 63					; 0000003fH
	sub	rax, rcx

; 915  : }

	ret	0
_LZCNT_ALT_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _ROTATE_L_UNIT
_TEXT	SEGMENT
x$ = 8
count$ = 16
_ROTATE_L_UNIT PROC					; COMDAT

; 741  : {

	mov	rax, rcx

; 742  : #ifdef _M_IX86
; 743  :     return (_rotl(x, count));
; 744  : #elif defined(_M_X64)
; 745  :     return (_rotl64(x, count));

	mov	ecx, edx
	rol	rax, cl

; 746  : #else
; 747  : #error unknown platform
; 748  : #endif
; 749  : }

	ret	0
_ROTATE_L_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _DIVIDE_CEILING_UNIT
_TEXT	SEGMENT
u$ = 8
v$ = 16
_DIVIDE_CEILING_UNIT PROC				; COMDAT

; 454  :     return ((u + v - 1) / v);

	lea	rax, QWORD PTR [rdx-1]
	mov	r8, rdx
	add	rax, rcx
	xor	edx, edx
	div	r8

; 455  : }

	ret	0
_DIVIDE_CEILING_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _FILL_MEMORY_UNIT
_TEXT	SEGMENT
d$ = 8
x$ = 16
count$ = 24
_FILL_MEMORY_UNIT PROC					; COMDAT

; 426  : {

	mov	QWORD PTR [rsp+8], rdi

; 427  : #ifdef _M_IX86
; 428  :     __stosd((unsigned long*)d, x, (unsigned long)count);
; 429  : #elif defined(_M_X64)
; 430  :     __stosq(d, x, count);

	mov	rdi, rcx
	mov	rax, rdx
	mov	rcx, r8
	rep stosq

; 431  : #else
; 432  : #error unknown platform
; 433  : #endif
; 434  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_FILL_MEMORY_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _FILL_MEMORY_64
_TEXT	SEGMENT
d$ = 8
x$ = 16
count$ = 24
_FILL_MEMORY_64 PROC					; COMDAT

; 420  : {

	mov	QWORD PTR [rsp+8], rdi

; 421  :     __stosq(d, x, count);

	mov	rdi, rcx
	mov	rax, rdx
	mov	rcx, r8
	rep stosq

; 422  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_FILL_MEMORY_64 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _FILL_MEMORY_32
_TEXT	SEGMENT
d$ = 8
x$ = 16
count$ = 24
_FILL_MEMORY_32 PROC					; COMDAT

; 414  : {

	mov	QWORD PTR [rsp+8], rdi

; 415  :     __stosd(( unsigned long*)d, x, count);

	mov	rdi, rcx
	mov	eax, edx
	mov	rcx, r8
	rep stosd

; 416  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_FILL_MEMORY_32 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _FILL_MEMORY_16
_TEXT	SEGMENT
d$ = 8
x$ = 16
count$ = 24
_FILL_MEMORY_16 PROC					; COMDAT

; 409  : {

	mov	QWORD PTR [rsp+8], rdi

; 410  :     __stosw(d, x, count);

	mov	rdi, rcx
	movzx	eax, dx
	mov	rcx, r8
	rep stosw

; 411  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_FILL_MEMORY_16 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _FILL_MEMORY_BYTE
_TEXT	SEGMENT
d$ = 8
x$ = 16
count$ = 24
_FILL_MEMORY_BYTE PROC					; COMDAT

; 404  : {

	mov	QWORD PTR [rsp+8], rdi

; 405  :     __stosb(d, x, count);

	mov	rdi, rcx
	movzx	eax, dl
	mov	rcx, r8
	rep stosb

; 406  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_FILL_MEMORY_BYTE ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _ZERO_MEMORY_64
_TEXT	SEGMENT
d$ = 8
count$ = 16
_ZERO_MEMORY_64 PROC					; COMDAT

; 370  : {

	mov	QWORD PTR [rsp+8], rdi

; 371  :     __stosq(d, 0, count);

	mov	rdi, rcx
	xor	eax, eax
	mov	rcx, rdx
	rep stosq

; 372  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_ZERO_MEMORY_64 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _ZERO_MEMORY_32
_TEXT	SEGMENT
d$ = 8
count$ = 16
_ZERO_MEMORY_32 PROC					; COMDAT

; 364  : {

	mov	QWORD PTR [rsp+8], rdi

; 365  :     __stosd((unsigned long*)d, 0, count);

	mov	rdi, rcx
	xor	eax, eax
	mov	rcx, rdx
	rep stosd

; 366  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_ZERO_MEMORY_32 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _ZERO_MEMORY_16
_TEXT	SEGMENT
d$ = 8
count$ = 16
_ZERO_MEMORY_16 PROC					; COMDAT

; 359  : {

	mov	QWORD PTR [rsp+8], rdi

; 360  :     __stosw(d, 0, count);

	mov	rdi, rcx
	xor	eax, eax
	mov	rcx, rdx
	rep stosw

; 361  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_ZERO_MEMORY_16 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _ZERO_MEMORY_BYTE
_TEXT	SEGMENT
d$ = 8
count$ = 16
_ZERO_MEMORY_BYTE PROC					; COMDAT

; 354  : {

	mov	QWORD PTR [rsp+8], rdi

; 355  :     __stosb(d, 0, count);

	mov	rdi, rcx
	xor	eax, eax
	mov	rcx, rdx
	rep stosb

; 356  : }

	mov	rdi, QWORD PTR [rsp+8]
	ret	0
_ZERO_MEMORY_BYTE ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
;	COMDAT _COPY_MEMORY_UNIT
_TEXT	SEGMENT
d$ = 8
s$ = 16
count$ = 24
_COPY_MEMORY_UNIT PROC					; COMDAT

; 326  : {

	mov	QWORD PTR [rsp+8], rsi
	mov	QWORD PTR [rsp+16], rdi

; 327  : #ifdef _M_IX86
; 328  :     __movsd((unsigned long *)d, (unsigned long *)s, (unsigned long)count);
; 329  : #elif defined(_M_X64)
; 330  :     __movsq(d, s, count);

	mov	rdi, rcx
	mov	rsi, rdx
	mov	rcx, r8
	rep movsq

; 331  : #else
; 332  : #error unknown platform
; 333  : #endif
; 334  : }

	mov	rsi, QWORD PTR [rsp+8]
	mov	rdi, QWORD PTR [rsp+16]
	ret	0
_COPY_MEMORY_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT PMC_Dispose
_TEXT	SEGMENT
p$ = 48
PMC_Dispose PROC					; COMDAT

; 538  : {

$LN32:

; 419  :     if (p == NULL || p->IS_STATIC)

	test	rcx, rcx
	je	SHORT $LN30@PMC_Dispos
	push	rbx
	sub	rsp, 32					; 00000020H
	test	BYTE PTR [rcx+32], 1

; 538  : {

	mov	rbx, rcx

; 419  :     if (p == NULL || p->IS_STATIC)

	jne	SHORT $LN8@PMC_Dispos

; 420  :         return;
; 421  :     CleanUpNumber(p);

	call	CleanUpNumber

; 321  :         __p[0] = DEFAULT_MEMORY_DATA;

	mov	rax, -3689348814741910324		; ccccccccccccccccH

; 423  :     HeapFree(hLocalHeap, 0, p);

	mov	r8, rbx

; 321  :         __p[0] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx], rax

; 423  :     HeapFree(hLocalHeap, 0, p);

	xor	edx, edx

; 322  :         __p[1] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+8], rax

; 323  :         __p[2] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+16], rax

; 324  :         __p[3] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+24], rax

; 325  :         __p[4] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+32], rax

; 326  :         __p[5] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+40], rax

; 327  :         __p[6] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+48], rax

; 423  :     HeapFree(hLocalHeap, 0, p);

	mov	rcx, QWORD PTR hLocalHeap
	call	QWORD PTR __imp_HeapFree
$LN8@PMC_Dispos:

; 539  :     NUMBER_HEADER* np = (NUMBER_HEADER*)p;
; 540  :     PMC_STATUS_CODE result = CheckNumber(np);
; 541  :     if (result != PMC_STATUS_OK)
; 542  :         return;
; 543  :     DeallocateNumber(np);
; 544  :     return;
; 545  : }

	add	rsp, 32					; 00000020H
	pop	rbx
$LN30@PMC_Dispos:
	ret	0
PMC_Dispose ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT Initialize_Memory
_TEXT	SEGMENT
feature$ = 48
Initialize_Memory PROC					; COMDAT

; 548  : {

$LN47:
	sub	rsp, 40					; 00000028H

; 280  :         __p[0] = 0;

	xor	eax, eax

; 549  :     PMC_STATUS_CODE result = PMC_STATUS_OK;
; 550  : 
; 551  :     BOOL number_zero_ok = TRUE;
; 552  :     if (result == PMC_STATUS_OK)
; 553  :     {
; 554  :         result = AttatchNumber(&number_zero, 0);
; 555  :         if (result == PMC_STATUS_OK)
; 556  :         {
; 557  :             CommitNumber(&number_zero);

	lea	rcx, OFFSET FLAT:number_zero
	xorps	xmm0, xmm0

; 284  :         __p[4] = 0;

	mov	QWORD PTR number_zero+32, rax

; 393  :     p->IS_STATIC = TRUE;

	mov	DWORD PTR number_zero+32, 1

; 280  :         __p[0] = 0;

	mov	QWORD PTR number_zero, rax

; 281  :         __p[1] = 0;
; 282  :         __p[2] = 0;

	movdqu	XMMWORD PTR number_zero+16, xmm0

; 372  :         p->UNIT_BIT_COUNT = 0;

	mov	QWORD PTR number_zero+8, rax

; 373  :         p->BLOCK_COUNT = 0;

	mov	QWORD PTR number_zero+40, rax

; 374  :         p->BLOCK = NULL;

	mov	QWORD PTR number_zero+48, rax

; 549  :     PMC_STATUS_CODE result = PMC_STATUS_OK;
; 550  : 
; 551  :     BOOL number_zero_ok = TRUE;
; 552  :     if (result == PMC_STATUS_OK)
; 553  :     {
; 554  :         result = AttatchNumber(&number_zero, 0);
; 555  :         if (result == PMC_STATUS_OK)
; 556  :         {
; 557  :             CommitNumber(&number_zero);

	call	CommitNumber

; 558  :             number_zero_ok = TRUE;
; 559  :         }
; 560  :     }
; 561  : 
; 562  :     if (result != PMC_STATUS_OK)
; 563  :     {
; 564  :         if (number_zero_ok)
; 565  :             DetatchNumber(&number_zero);
; 566  :     }
; 567  : 
; 568  :     return (result);

	xor	eax, eax

; 569  : }

	add	rsp, 40					; 00000028H
	ret	0
Initialize_Memory ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT DuplicateNumber
_TEXT	SEGMENT
x$ = 48
op$ = 56
DuplicateNumber PROC					; COMDAT

; 514  : {

$LN18:
	mov	QWORD PTR [rsp+24], rsi
	push	r14
	sub	rsp, 32					; 00000020H

; 515  :     if (x->IS_STATIC)

	mov	eax, DWORD PTR [rcx+32]
	mov	r14, rdx
	mov	rsi, rcx
	test	al, 1
	je	SHORT $LN2@DuplicateN

; 516  :     {
; 517  :         *op = x;

	mov	QWORD PTR [rdx], rcx

; 518  :         return (PMC_STATUS_OK);

	xor	eax, eax

; 534  : }

	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
$LN2@DuplicateN:

; 519  :     }
; 520  :     if (x->IS_ZERO)

	test	al, 2
	je	SHORT $LN3@DuplicateN

; 521  :     {
; 522  :         *op = &number_zero;

	lea	rax, OFFSET FLAT:number_zero
	mov	QWORD PTR [rdx], rax

; 523  :         return (PMC_STATUS_OK);

	xor	eax, eax

; 534  : }

	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
$LN3@DuplicateN:

; 399  :     NUMBER_HEADER* p = (NUMBER_HEADER*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, sizeof(NUMBER_HEADER));

	mov	edx, 8
	mov	QWORD PTR [rsp+48], rbx
	mov	QWORD PTR [rsp+56], rdi

; 524  :     }
; 525  :     __UNIT_TYPE x_bit_count = x->UNIT_BIT_COUNT;

	mov	rdi, QWORD PTR [rcx+8]

; 399  :     NUMBER_HEADER* p = (NUMBER_HEADER*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, sizeof(NUMBER_HEADER));

	mov	rcx, QWORD PTR hLocalHeap
	lea	r8d, QWORD PTR [rdx+48]
	call	QWORD PTR __imp_HeapAlloc
	mov	rbx, rax

; 400  :     if (p == NULL)

	test	rax, rax
	jne	SHORT $LN7@DuplicateN

; 401  :         return (PMC_STATUS_NOT_ENOUGH_MEMORY);

	lea	eax, QWORD PTR [rbx-5]
	jmp	SHORT $LN16@DuplicateN
$LN7@DuplicateN:

; 402  :     PMC_STATUS_CODE result = InitializeNumber(p, bit_count, light_check_code);

	xor	r8d, r8d
	mov	rdx, rdi
	mov	rcx, rbx
	call	InitializeNumber

; 403  :     if (result != PMC_STATUS_OK)

	test	eax, eax
	jne	SHORT $LN16@DuplicateN

; 404  :         return (result);
; 405  :     p->IS_STATIC = FALSE;

	and	DWORD PTR [rbx+32], -2			; fffffffeH
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 454  :     return ((u + v - 1) / v);

	lea	rcx, QWORD PTR [rdi+63]

; 330  :     __movsq(d, s, count);

	mov	rdi, QWORD PTR [rbx+48]
	mov	rsi, QWORD PTR [rsi+48]

; 454  :     return ((u + v - 1) / v);

	shr	rcx, 6

; 330  :     __movsq(d, s, count);

	rep movsq
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 531  :     CommitNumber(o);

	mov	rcx, rbx
	call	CommitNumber

; 532  :     *op = o;
; 533  :     return (PMC_STATUS_OK);

	xor	eax, eax
	mov	QWORD PTR [r14], rbx
$LN16@DuplicateN:

; 534  : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rdi, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
DuplicateNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CheckNumber
_TEXT	SEGMENT
p$ = 8
CheckNumber PROC					; COMDAT

; 498  : #ifdef _DEBUG
; 499  :     if (!p->IS_ZERO)
; 500  :     {
; 501  :         PMC_STATUS_CODE result;
; 502  :         if ((result = CheckBlock(p->BLOCK)) != PMC_STATUS_OK)
; 503  :             return (result);
; 504  :         __UNIT_TYPE desired_hash_code = CalculateCheckCode(p->BLOCK, p->UNIT_WORD_COUNT);
; 505  :         if (desired_hash_code != p->HASH_CODE)
; 506  :             return (PMC_STATUS_BAD_BUFFER);
; 507  :     }
; 508  : #endif
; 509  :     return (PMC_STATUS_OK);

	xor	eax, eax

; 510  : }

	ret	0
CheckNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CommitNumber
_TEXT	SEGMENT
p$ = 48
CommitNumber PROC					; COMDAT

; 464  : {

$LN39:
	sub	rsp, 40					; 00000028H
	mov	r10, rcx

; 223  :     if (buffer != NULL)

	xor	r11d, r11d

; 465  :     CommitBlock(p->BLOCK);

	mov	rcx, QWORD PTR [rcx+48]

; 223  :     if (buffer != NULL)

	test	rcx, rcx
	je	SHORT $LN8@CommitNumb

; 224  :     {
; 225  :         --buffer;
; 226  :         __UNIT_TYPE words = buffer[0];
; 227  : #ifdef _DEBUG
; 228  :         __UNIT_TYPE code = CalculateCheckCode(&buffer[1], words);
; 229  : #else
; 230  :         __UNIT_TYPE code = 0;
; 231  : #endif
; 232  :         buffer[words + 1] = code;

	mov	rax, QWORD PTR [rcx-8]
	mov	QWORD PTR [rcx+rax*8], r11
	mov	rcx, QWORD PTR [r10+48]
$LN8@CommitNumb:

; 466  :     p->UNIT_BIT_COUNT = GetEffectiveBitLength(p->BLOCK, p->BLOCK_COUNT, &p->UNIT_WORD_COUNT);

	mov	r9, QWORD PTR [r10+40]

; 428  :     if (p == NULL)

	test	rcx, rcx
	je	SHORT $LN12@CommitNumb

; 429  :     {
; 430  :         *effective_word_count = 0;
; 431  :         return (0);
; 432  :     }
; 433  :     p += word_count;

	lea	rax, QWORD PTR [rcx+r9*8]

; 434  :     while (word_count != 0)

	test	r9, r9
	je	SHORT $LN12@CommitNumb
$LL11@CommitNumb:

; 435  :     {
; 436  :         --p;
; 437  :         if (*p != 0)

	cmp	QWORD PTR [rax-8], r11
	lea	rax, QWORD PTR [rax-8]
	jne	SHORT $LN29@CommitNumb

; 441  :         }
; 442  :         --word_count;

	sub	r9, 1
	jne	SHORT $LL11@CommitNumb
$LN12@CommitNumb:

; 466  :     p->UNIT_BIT_COUNT = GetEffectiveBitLength(p->BLOCK, p->BLOCK_COUNT, &p->UNIT_WORD_COUNT);

	mov	r9, r11
	mov	QWORD PTR [r10], r11
$LN10@CommitNumb:
	mov	QWORD PTR [r10+8], r9

; 467  :     if (p->UNIT_BIT_COUNT <= 0)

	test	r9, r9
	jne	SHORT $LN2@CommitNumb

; 468  :     {
; 469  :         p->HASH_CODE = 0;
; 470  :         p->IS_ZERO = TRUE;

	mov	eax, DWORD PTR [r10+32]
	and	eax, -21				; ffffffebH
	mov	QWORD PTR [r10+16], r11

; 471  :         p->IS_ONE = FALSE;
; 472  :         p->IS_EVEN = TRUE;
; 473  :         p->TRAILING_ZERO_BITS_COUNT = 0;
; 474  :         p->IS_POWER_OF_TWO = FALSE;

	or	eax, 10
	mov	QWORD PTR [r10+24], r11

; 493  :     }
; 494  : }

	mov	DWORD PTR [r10+32], eax
	add	rsp, 40					; 00000028H
	ret	0
$LN29@CommitNumb:

; 439  :             *effective_word_count = word_count;

	mov	QWORD PTR [r10], r9

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	mov	rcx, QWORD PTR [rax]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 890  :     if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN17@CommitNumb

; 891  :         return (sizeof(x) * 8);

	mov	eax, 64					; 00000040H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	shl	r9, 6
	sub	r9, rax
	jmp	SHORT $LN10@CommitNumb
$LN17@CommitNumb:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 904  :     _BitScanReverse64(&pos, x);

	bsr	rcx, rcx

; 914  :     return (sizeof(x) * 8 - 1 - pos);

	mov	eax, 63					; 0000003fH
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	shl	r9, 6
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 914  :     return (sizeof(x) * 8 - 1 - pos);

	sub	rax, rcx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 440  :             return (word_count * __UNIT_TYPE_BIT_COUNT - _LZCNT_ALT_UNIT(*p));

	sub	r9, rax
	jmp	SHORT $LN10@CommitNumb
$LN2@CommitNumb:

; 475  :     }
; 476  :     else if (p->UNIT_BIT_COUNT == 1)

	mov	rdx, QWORD PTR [r10]
	mov	rcx, QWORD PTR [r10+48]
	call	CalculateCheckCode
	mov	QWORD PTR [r10+16], rax
	mov	edx, DWORD PTR [r10+32]
	and	edx, -3					; fffffffdH
	mov	DWORD PTR [r10+32], edx
	mov	rcx, QWORD PTR [r10+48]
	cmp	r9, 1
	jne	SHORT $LN4@CommitNumb

; 477  :     {
; 478  :         p->HASH_CODE = CalculateCheckCode(p->BLOCK, p->UNIT_WORD_COUNT);
; 479  :         p->IS_ZERO = FALSE;
; 480  :         p->IS_ONE = p->BLOCK[0] == 1; // 無条件でTRUEでも大丈夫だが念のため。

	mov	rax, QWORD PTR [rcx]
	mov	ecx, 4

; 481  :         p->IS_EVEN = FALSE;
; 482  :         p->TRAILING_ZERO_BITS_COUNT = 0;

	mov	QWORD PTR [r10+24], r11
	cmp	rax, r9
	cmove	r11d, ecx
	and	edx, -5					; fffffffbH

; 483  :         p->IS_POWER_OF_TWO = TRUE;

	or	r11d, edx
	and	r11d, -9				; fffffff7H
	or	r11d, 16

; 493  :     }
; 494  : }

	mov	DWORD PTR [r10+32], r11d
	add	rsp, 40					; 00000028H
	ret	0
$LN4@CommitNumb:

; 484  :     }
; 485  :     else
; 486  :     {
; 487  :         p->HASH_CODE = CalculateCheckCode(p->BLOCK, p->UNIT_WORD_COUNT);
; 488  :         p->IS_ZERO = FALSE;
; 489  :         p->IS_ONE = FALSE;

	and	edx, -5					; fffffffbH
	mov	DWORD PTR [r10+32], edx

; 490  :         p->IS_EVEN = !(p->BLOCK[0] & 1);

	mov	eax, DWORD PTR [rcx]
	shl	eax, 3
	not	eax
	xor	eax, edx
	and	eax, 8
	xor	eax, edx

; 450  :     __UNIT_TYPE bit_count = 0;

	mov	rdx, r11

; 490  :         p->IS_EVEN = !(p->BLOCK[0] & 1);

	mov	DWORD PTR [r10+32], eax

; 491  :         p->TRAILING_ZERO_BITS_COUNT = GetTrailingZeroBitCount(p->BLOCK, p->UNIT_WORD_COUNT);

	mov	rax, QWORD PTR [r10]

; 451  :     while (word_count > 0)

	test	rax, rax
	je	SHORT $LN21@CommitNumb
	npad	4
$LL20@CommitNumb:

; 452  :     {
; 453  :         --word_count;
; 454  :         if (*p != 0)

	mov	r8, QWORD PTR [rcx]
	dec	rax
	test	r8, r8
	jne	SHORT $LN30@CommitNumb

; 456  :         bit_count += __UNIT_TYPE_BIT_COUNT;

	add	rdx, 64					; 00000040H

; 457  :         ++p;

	add	rcx, 8
	test	rax, rax
	jne	SHORT $LL20@CommitNumb
$LN21@CommitNumb:

; 458  :     }
; 459  :     // このルートには到達しないはず
; 460  :     return (0);

	mov	rax, r11
$LN19@CommitNumb:

; 491  :         p->TRAILING_ZERO_BITS_COUNT = GetTrailingZeroBitCount(p->BLOCK, p->UNIT_WORD_COUNT);

	mov	QWORD PTR [r10+24], rax

; 492  :         p->IS_POWER_OF_TWO = p->TRAILING_ZERO_BITS_COUNT + 1 == p->UNIT_BIT_COUNT;

	mov	ecx, 16
	inc	rax
	cmp	rax, r9
	mov	eax, DWORD PTR [r10+32]
	cmove	r11d, ecx
	and	eax, -17				; ffffffefH
	or	r11d, eax

; 493  :     }
; 494  : }

	mov	DWORD PTR [r10+32], r11d
	add	rsp, 40					; 00000028H
	ret	0
$LN30@CommitNumb:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 984  :     _BitScanForward64(&pos, x);

	bsf	rax, r8
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 455  :             return (bit_count + _TZCNT_ALT_UNIT(*p));

	add	rax, rdx
	jmp	SHORT $LN19@CommitNumb
CommitNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT DeallocateNumber
_TEXT	SEGMENT
p$ = 48
DeallocateNumber PROC					; COMDAT

; 418  : {

$LN27:

; 419  :     if (p == NULL || p->IS_STATIC)

	test	rcx, rcx
	je	SHORT $LN25@Deallocate
	push	rbx
	sub	rsp, 32					; 00000020H
	test	BYTE PTR [rcx+32], 1
	mov	rbx, rcx
	jne	SHORT $LN3@Deallocate

; 420  :         return;
; 421  :     CleanUpNumber(p);

	call	CleanUpNumber

; 321  :         __p[0] = DEFAULT_MEMORY_DATA;

	mov	rax, -3689348814741910324		; ccccccccccccccccH

; 422  :     FillNumberHeader(p);
; 423  :     HeapFree(hLocalHeap, 0, p);

	mov	r8, rbx

; 321  :         __p[0] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx], rax

; 422  :     FillNumberHeader(p);
; 423  :     HeapFree(hLocalHeap, 0, p);

	xor	edx, edx

; 322  :         __p[1] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+8], rax

; 323  :         __p[2] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+16], rax

; 324  :         __p[3] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+24], rax

; 325  :         __p[4] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+32], rax

; 326  :         __p[5] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+40], rax

; 327  :         __p[6] = DEFAULT_MEMORY_DATA;

	mov	QWORD PTR [rbx+48], rax

; 422  :     FillNumberHeader(p);
; 423  :     HeapFree(hLocalHeap, 0, p);

	mov	rcx, QWORD PTR hLocalHeap
	call	QWORD PTR __imp_HeapFree
$LN3@Deallocate:

; 424  : }

	add	rsp, 32					; 00000020H
	pop	rbx
$LN25@Deallocate:
	ret	0
DeallocateNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT DetatchNumber
_TEXT	SEGMENT
p$ = 8
DetatchNumber PROC					; COMDAT

; 412  :     if (p == NULL || !p->IS_STATIC)

	test	rcx, rcx
	je	SHORT $LN3@DetatchNum
	test	BYTE PTR [rcx+32], 1
	jne	CleanUpNumber
$LN3@DetatchNum:

; 413  :         return;
; 414  :     CleanUpNumber(p);
; 415  : }

	ret	0
DetatchNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT AllocateNumber
_TEXT	SEGMENT
pp$ = 48
bit_count$ = 56
light_check_code$ = 64
AllocateNumber PROC					; COMDAT

; 398  : {

$LN6:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rsi, r8

; 399  :     NUMBER_HEADER* p = (NUMBER_HEADER*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, sizeof(NUMBER_HEADER));

	mov	edx, 8
	mov	rdi, rcx
	mov	rcx, QWORD PTR hLocalHeap
	lea	r8d, QWORD PTR [rdx+48]
	call	QWORD PTR __imp_HeapAlloc
	mov	rbx, rax

; 400  :     if (p == NULL)

	test	rax, rax
	jne	SHORT $LN2@AllocateNu

; 401  :         return (PMC_STATUS_NOT_ENOUGH_MEMORY);

	lea	eax, QWORD PTR [rbx-5]
	jmp	SHORT $LN1@AllocateNu
$LN2@AllocateNu:

; 402  :     PMC_STATUS_CODE result = InitializeNumber(p, bit_count, light_check_code);

	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, rbx
	call	InitializeNumber

; 403  :     if (result != PMC_STATUS_OK)

	test	eax, eax
	jne	SHORT $LN1@AllocateNu

; 404  :         return (result);
; 405  :     p->IS_STATIC = FALSE;

	and	DWORD PTR [rbx+32], -2			; fffffffeH

; 406  :     *pp = p;

	mov	QWORD PTR [rdi], rbx
$LN1@AllocateNu:

; 407  :     return (PMC_STATUS_OK);
; 408  : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
AllocateNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT AttatchNumber
_TEXT	SEGMENT
p$ = 48
bit_count$ = 56
AttatchNumber PROC					; COMDAT

; 389  : {

$LN5:
	push	rbx
	sub	rsp, 32					; 00000020H

; 390  :     PMC_STATUS_CODE result = InitializeNumber(p, bit_count, NULL);

	xor	r8d, r8d
	mov	rbx, rcx
	call	InitializeNumber

; 391  :     if (result != PMC_STATUS_OK)

	test	eax, eax
	jne	SHORT $LN1@AttatchNum

; 392  :         return (result);
; 393  :     p->IS_STATIC = TRUE;

	or	DWORD PTR [rbx+32], 1
$LN1@AttatchNum:

; 394  :     return (PMC_STATUS_OK);
; 395  : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
AttatchNumber ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT CheckBlockLight
_TEXT	SEGMENT
buffer$ = 8
code$ = 16
CheckBlockLight PROC					; COMDAT

; 258  : #ifdef _DEBUG
; 259  :     if (buffer == NULL)
; 260  :         return (PMC_STATUS_OK);
; 261  :     --buffer;
; 262  :     __UNIT_TYPE words = buffer[0];
; 263  :     __UNIT_TYPE code_desired = buffer[words + 1] ^ (__UNIT_TYPE)&buffer[words + 1];
; 264  :     __UNIT_TYPE code_actual = code;
; 265  :     if (code_actual == code_desired)
; 266  :         return (PMC_STATUS_OK);
; 267  :     else
; 268  :         return (PMC_STATUS_BAD_BUFFER);
; 269  : #else
; 270  :     return (PMC_STATUS_OK);

	xor	eax, eax

; 271  : #endif
; 272  : }

	ret	0
CheckBlockLight ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT DeallocateBlock
_TEXT	SEGMENT
buffer$ = 48
buffer_words$ = 56
DeallocateBlock PROC					; COMDAT

; 202  : {

$LN9:
	sub	rsp, 40					; 00000028H

; 203  : 	if (buffer != NULL)

	test	rcx, rcx
	je	SHORT $LN4@Deallocate

; 204  : 	{
; 205  :         __UNIT_TYPE* p = buffer - 1;
; 206  :         if (*p != buffer_words)

	cmp	QWORD PTR [rcx-8], rdx
	lea	r8, QWORD PTR [rcx-8]
	jne	SHORT $LN4@Deallocate

; 207  :         {
; 208  :             // もし、buffer の指す内容が壊れていることが明らかならば、二重解放の恐れがあるので解放処理はしない。
; 209  :         }
; 210  :         else
; 211  :         {
; 212  :             // 使用済みのバッファを既定のデータで塗りつぶす。
; 213  :             _FILL_MEMORY_UNIT(p, DEFAULT_MEMORY_DATA, buffer_words + 2);

	lea	rcx, QWORD PTR [rdx+2]
	mov	QWORD PTR [rsp+32], rdi
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 430  :     __stosq(d, x, count);

	mov	rdi, r8
	mov	rax, -3689348814741910324		; ccccccccccccccccH
	rep stosq
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 215  :             HeapFree(hLocalHeap, 0, p);

	mov	rcx, QWORD PTR hLocalHeap
	xor	edx, edx
	mov	rdi, QWORD PTR [rsp+32]

; 216  :         }
; 217  : 	}
; 218  : }

	add	rsp, 40					; 00000028H

; 215  :             HeapFree(hLocalHeap, 0, p);

	rex_jmp	QWORD PTR __imp_HeapFree
	mov	rdi, QWORD PTR [rsp+32]
$LN4@Deallocate:

; 216  :         }
; 217  : 	}
; 218  : }

	add	rsp, 40					; 00000028H
	ret	0
DeallocateBlock ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT AllocateBlock
_TEXT	SEGMENT
bits$ = 48
allocated_block_words$ = 56
code$ = 64
AllocateBlock PROC					; COMDAT

; 160  : {

$LN8:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 454  :     return ((u + v - 1) / v);

	lea	rbx, QWORD PTR [rcx+63]
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 160  : {

	mov	rdi, r8

; 168  : 	__UNIT_TYPE* buffer = (__UNIT_TYPE*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, bytes);

	mov	rcx, QWORD PTR hLocalHeap
	mov	rsi, rdx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_internal.h

; 454  :     return ((u + v - 1) / v);

	shr	rbx, 6
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c

; 168  : 	__UNIT_TYPE* buffer = (__UNIT_TYPE*)HeapAlloc(hLocalHeap, HEAP_ZERO_MEMORY, bytes);

	mov	edx, 8
	lea	r8, QWORD PTR [rbx*8+16]
	call	QWORD PTR __imp_HeapAlloc
	mov	rcx, rax

; 169  : 	if (buffer == NULL)

	test	rax, rax
	jne	SHORT $LN2@AllocateBl

; 196  :     return (&buffer[1]);
; 197  : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN2@AllocateBl:

; 170  : 		return (NULL);
; 171  : 	buffer[0] = words1;

	mov	QWORD PTR [rax], rbx

; 172  :     *allocated_block_words = words1;
; 173  : #ifdef _DEBUG
; 174  :     // 乱数もどきを生成する。
; 175  : #ifdef _M_IX86
; 176  :     __UNIT_TYPE r = GetTickCount();
; 177  : #elif defined(_M_IX64)
; 178  : #ifdef _MSC_VER
; 179  :     __UNIT_TYPE r = GetTickCount64();
; 180  : #elif defined(__GNUC__)
; 181  :     _UINT32_T temp = GetTickCount();
; 182  :     __UNIT_TYPE r = _FROMWORDTODWORD(temp, temp);
; 183  : #else
; 184  : #error unknown compiler
; 185  : #endif
; 186  : #else
; 187  : #error unknown platform
; 188  : #endif
; 189  :     __UNIT_TYPE check_code = configuration_info.MEMORY_VERIFICATION_ENABLED ? CalculateCheckCode(&buffer[1], words1) : CHECK_CODE_INIT | r;
; 190  : #else
; 191  :     __UNIT_TYPE check_code = 0;
; 192  : #endif
; 193  :     buffer[words1 + 1] = check_code ^ (__UNIT_TYPE)&buffer[words1 + 1];

	lea	rax, QWORD PTR [rbx+1]
	mov	QWORD PTR [rsi], rbx
	lea	rax, QWORD PTR [rcx+rax*8]
	mov	QWORD PTR [rax], rax

; 194  :     if (code != NULL)

	test	rdi, rdi
	je	SHORT $LN3@AllocateBl

; 195  :         *code = check_code;

	mov	QWORD PTR [rdi], 0
$LN3@AllocateBl:

; 196  :     return (&buffer[1]);
; 197  : }

	mov	rbx, QWORD PTR [rsp+48]
	lea	rax, QWORD PTR [rcx+8]
	mov	rsi, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
AllocateBlock ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT DeallocateHeapArea
_TEXT	SEGMENT
DeallocateHeapArea PROC					; COMDAT

; 580  : {

$LN5:
	sub	rsp, 40					; 00000028H

; 581  :     if (hLocalHeap != NULL)

	mov	rcx, QWORD PTR hLocalHeap
	test	rcx, rcx
	je	SHORT $LN2@Deallocate

; 582  :     {
; 583  :         HeapDestroy(hLocalHeap);

	call	QWORD PTR __imp_HeapDestroy

; 584  :         hLocalHeap = NULL;

	mov	QWORD PTR hLocalHeap, 0
$LN2@Deallocate:

; 585  :     }
; 586  : }

	add	rsp, 40					; 00000028H
	ret	0
DeallocateHeapArea ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\memory.c
;	COMDAT AllocateHeapArea
_TEXT	SEGMENT
AllocateHeapArea PROC					; COMDAT

; 572  : {

$LN5:
	sub	rsp, 40					; 00000028H

; 573  :     hLocalHeap = HeapCreate(0, 0x1000, 0);

	xor	r8d, r8d
	mov	edx, 4096				; 00001000H
	xor	ecx, ecx
	call	QWORD PTR __imp_HeapCreate

; 574  :     if (hLocalHeap == NULL)

	xor	ecx, ecx
	mov	QWORD PTR hLocalHeap, rax
	test	rax, rax
	setne	cl
	mov	eax, ecx

; 575  :         return (FALSE);
; 576  :     return (TRUE);
; 577  : }

	add	rsp, 40					; 00000028H
	ret	0
AllocateHeapArea ENDP
_TEXT	ENDS
END
