/*
 * The MIT License
 *
 * Copyright 2019 Palmtree Software.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/* 
 * File:   pmc_subtruct.c
 * Author: Lunor Kisasage
 * 
 * Created on 2019/01/05, 22:34
 */


#include <windows.h>
#include "pmc_internal.h"
#include "autogenerated.h"


static PMC_STATUS_CODE DoBorrow(char c, __UNIT_TYPE* xp, __UNIT_TYPE x_count, __UNIT_TYPE* op, __UNIT_TYPE o_count)
{
    // 桁借りを続く限り行う
    for (;;)
    {
        if (x_count <= 0)
        {
            // x の最上位まで達してしまった場合

            if (c)
            {
                // かつそれでも桁借りを行う必要がある場合

                // 減算結果が負になってしまったので呼び出し元に通知する。
                return (PMC_STATUS_INTERNAL_BORROW);
            }

            // xの最上位に達してしまった場合はいずれにしろループを中断して正常復帰する。

            return (PMC_STATUS_OK);
        }
        else if (c)
        {
            // xの最上位に達しておらず、かつボローが立っている場合

            // 桁借りを継続する
            c = _SUBTRUCT_UNIT(c, *xp++, 0, op++);
            --x_count;
            --o_count;
        }
        else
        {
            // xの最上位に達しておらず、かつボローが立っていない場合

            // 桁借りを中断し、xの残りのデータをzにそのまま複写し、正常復帰する。
            while (x_count > 0)
            {
                *op++ = *xp++;
                --x_count;
                --o_count;
            }
            return (PMC_STATUS_OK);
        }
    }
}

static PMC_STATUS_CODE Subtruct_X_1W(NUMBER_HEADER* x, __UNIT_TYPE y, NUMBER_HEADER* z)
{
    __UNIT_TYPE x_count = x->UNIT_WORD_COUNT;
    __UNIT_TYPE z_count = z->BLOCK_COUNT;
    __UNIT_TYPE* xp = &x->BLOCK[0];
    __UNIT_TYPE* zp = &z->BLOCK[0];
    char c;



    // 最下桁の減算を行う
    c = _SUBTRUCT_UNIT(0, *xp++, y, zp++);
    --x_count;
    --z_count;

    // 残りの桁の繰上りを行い復帰する。
    return (DoBorrow(c, xp, x_count, zp, z_count));
}

// y_hi はゼロであってはならない。
static PMC_STATUS_CODE Subtruct_X_2W(NUMBER_HEADER* x, __UNIT_TYPE y_hi, __UNIT_TYPE y_lo, NUMBER_HEADER* z)
{
    __UNIT_TYPE x_count = x->UNIT_WORD_COUNT;
    __UNIT_TYPE z_count = z->BLOCK_COUNT;
    __UNIT_TYPE* xp = &x->BLOCK[0];
    __UNIT_TYPE* zp = &z->BLOCK[0];
    char c;

    if (x_count < 2)
    {
        // x が 1 ワードしかなかった場合

        // 明らかに演算結果が負になるのでエラーを通知する。
        return (PMC_STATUS_INTERNAL_BORROW);
    }
    else
    {
        // x が 2 ワード以上あった場合

        // 最下位のワードの減算をする
        c = _SUBTRUCT_UNIT(0, *xp++, y_lo, zp++);

        // 最下位から 2 番目のワードの減算をする。
        c = _SUBTRUCT_UNIT(c, *xp++, y_hi, zp++);
        x_count -= 2;
        z_count -= 2;

        // 残りの桁の繰り上がりを計算し、復帰する。
        return (DoBorrow(c, xp, x_count, zp, z_count));
    }
}

// 減算の実装。x のワード数は y のワード数以上でなければならない。また、x と y はどちらもゼロであってはならない。
static PMC_STATUS_CODE Subtruct_X_X(NUMBER_HEADER* x, NUMBER_HEADER* y, NUMBER_HEADER* z)
{
    __UNIT_TYPE x_count = x->UNIT_WORD_COUNT;
    __UNIT_TYPE y_count = y->UNIT_WORD_COUNT;
    __UNIT_TYPE z_count = z->BLOCK_COUNT;
    __UNIT_TYPE* xp = &x->BLOCK[0];
    __UNIT_TYPE* yp = &y->BLOCK[0];
    __UNIT_TYPE* zp = &z->BLOCK[0];
    char c = 0;

    // まず 32 ワードずつ減算をする。
    __UNIT_TYPE count = y_count >> 5;
    while (count != 0)
    {
        c= _SUBTRUCT_32WORDS_SBB(c, xp, yp, zp);
        xp += 32;
        yp += 32;
        zp += 32;
        --count;
    }
    // この時点で未処理の桁は 32 ワード未満のはず

    // 未処理の桁が 16 ワード以上あるなら 16 ワード減算を行う。
    if (y_count & 0x10)
    {
        c = _SUBTRUCT_16WORDS_SBB(c, xp, yp, zp);
        xp += 16;
        yp += 16;
        zp += 16;
    }
    // この時点で未処理の桁は 16 ワード未満のはず

    // 未処理の桁が 8 ワード以上あるなら 8 ワード減算を行う。
    if (y_count & 0x8)
    {
        c = _SUBTRUCT_8WORDS_SBB(c, xp, yp, zp);
        xp += 8;
        yp += 8;
        zp += 8;
    }
    // この時点で未処理の桁は 8 ワード未満のはず

    // 未処理の桁が 4 ワード以上あるなら 4 ワード減算を行う。
    if (y_count & 0x4)
    {
        c = _SUBTRUCT_4WORDS_SBB(c, xp, yp, zp);
        xp += 4;
        yp += 4;
        zp += 4;
    }
    // この時点で未処理の桁は 4 ワード未満のはず

    // 未処理の桁が 2 ワード以上あるなら 2 ワード減算を行う。
    if (y_count & 0x2)
    {
        c = _SUBTRUCT_2WORDS_SBB(c, xp, yp, zp);
        xp += 2;
        yp += 2;
        zp += 2;
    }
    // この時点で未処理の桁は 2 ワード未満のはず

    // 未処理の桁が 1 ワード以上あるなら 1 ワード減算を行う。
    if (y_count & 1)
        c = _SUBTRUCT_UNIT(c, *xp++, *yp++, zp++);

    // 残りの桁の繰り上がりを計算し、復帰する。
    return (DoBorrow(c, xp, x_count - y_count, zp, z_count - y_count));
}

PMC_STATUS_CODE __PMC_CALL PMC_Subtruct_X_I(HANDLE x, _UINT32_T y, HANDLE* o)
{
    if (__UNIT_TYPE_BIT_COUNT < sizeof(y) * 8)
    {
        // _UINT32_T が 1 ワードで表現しきれない処理系には対応しない
        return (PMC_STATUS_INTERNAL_ERROR);
    }
    if (x == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    if (o == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    NUMBER_HEADER* nx = (NUMBER_HEADER*)x;
    PMC_STATUS_CODE result;
    if ((result = CheckNumber(nx)) != PMC_STATUS_OK)
        return (result);
    NUMBER_HEADER* nz;
    if (nx->IS_ZERO)
    {
        // x がゼロである場合

        if (y == 0)
        {
            // y がゼロである場合

            // x と y がともにゼロであるので、演算結果のゼロを呼び出し元に返す。
            *o = &number_zero;
        }
        else
        {
            // y がゼロではない場合

            // 演算結果は負となってしまうのでエラーを返す。
            return (PMC_STATUS_OUT_OF_RANGE);
        }
    }
    else
    {
        // x がゼロではない場合

        if (y == 0)
        {
            // y がゼロである場合

            // 演算結果となる x の値を持つ NUMBER_HEADER 構造体を獲得し、呼び出し元へ返す。
            if ((result = DuplicateNumber(nx, &nz)) != PMC_STATUS_OK)
                return (result);
        }
        else
        {
            // x と y がともにゼロではない場合

            // x と y の差を計算する
            __UNIT_TYPE x_bit_count = nx->UNIT_BIT_COUNT;
            __UNIT_TYPE y_bit_count = sizeof(y) * 8 - _LZCNT_ALT_32(y);
            if (x_bit_count < y_bit_count)
            {
                // 演算結果は負となってしまうのでエラーを返す。
                return (PMC_STATUS_OUT_OF_RANGE);
            }
            __UNIT_TYPE z_bit_count = x_bit_count;
            __UNIT_TYPE nz_light_check_code;
            if ((result = AllocateNumber(&nz, z_bit_count, &nz_light_check_code)) != PMC_STATUS_OK)
                return (result);
            if ((result = Subtruct_X_1W(nx, y, nz)) != PMC_STATUS_OK)
            {
                DeallocateNumber(nz);
                return (result == PMC_STATUS_INTERNAL_BORROW ? PMC_STATUS_OUT_OF_RANGE : result);
            }
            if ((result = CheckBlockLight(nz->BLOCK, nz_light_check_code)) != PMC_STATUS_OK)
                return (result);
            CommitNumber(nz);
            if (nz->IS_ZERO)
            {
                DeallocateNumber(nz);
                nz = &number_zero;
            }
        }
        *o = nz;
    }
#ifdef _DEBUG
    if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
        return (result);
#endif
    return (PMC_STATUS_OK);
}

PMC_STATUS_CODE __PMC_CALL PMC_Subtruct_X_L(HANDLE x, _UINT64_T y, HANDLE* o)
{
    if (__UNIT_TYPE_BIT_COUNT * 2 < sizeof(y) * 8)
    {
        // _UINT64_T が 2 ワードで表現しきれない処理系には対応しない
        return (PMC_STATUS_INTERNAL_ERROR);
    }
    if (x == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    if (o == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    NUMBER_HEADER* nx = (NUMBER_HEADER*)x;
    PMC_STATUS_CODE result;
    if ((result = CheckNumber(nx)) != PMC_STATUS_OK)
        return (result);
    NUMBER_HEADER* nz;
    if (nx->IS_ZERO)
    {
        // x がゼロである場合

        if (y == 0)
        {
            // y がゼロである場合

            // x と y がともにゼロであるので、演算結果のゼロを呼び出し元に返す。
            *o = &number_zero;
        }
        else
        {
            // y がゼロではない場合

            // 演算結果は負となってしまうのでエラーを返す。
            return (PMC_STATUS_OUT_OF_RANGE);
        }
    }
    else
    {
        // x がゼロではない場合

        if (y == 0)
        {
            // y がゼロである場合

            // 演算結果となる x の値を持つ NUMBER_HEADER 構造体を獲得し、呼び出し元へ返す。
            if ((result = DuplicateNumber(nx, &nz)) != PMC_STATUS_OK)
                return (result);
        }
        else
        {
            // x と y がともにゼロではない場合

            // x と y の差を計算する
            if (__UNIT_TYPE_BIT_COUNT < sizeof(y) * 8)
            {
                // _UINT64_T が 1 ワードで表現しきれない場合

                __UNIT_TYPE x_bit_count = nx->UNIT_BIT_COUNT;
                _UINT32_T y_hi;
                _UINT32_T y_lo = _FROMDWORDTOWORD(y, &y_hi);
                if (y_hi == 0)
                {
                    // y の値が 32bit で表現可能な場合
                    __UNIT_TYPE y_bit_count = sizeof(y_lo) * 8 - _LZCNT_ALT_32(y_lo);
                    if (x_bit_count < y_bit_count)
                    {
                        // 演算結果は負となってしまうのでエラーを返す。
                        return (PMC_STATUS_OUT_OF_RANGE);
                    }
                    __UNIT_TYPE z_bit_count = x_bit_count;
                    __UNIT_TYPE nz_light_check_code;
                    if ((result = AllocateNumber(&nz, z_bit_count, &nz_light_check_code)) != PMC_STATUS_OK)
                        return (result);
                    if ((result = Subtruct_X_1W(nx, y_lo, nz)) != PMC_STATUS_OK)
                    {
                        DeallocateNumber(nz);
                        return (result == PMC_STATUS_INTERNAL_BORROW ? PMC_STATUS_OUT_OF_RANGE : result);
                    }
                    if ((result = CheckBlockLight(nz->BLOCK, nz_light_check_code)) != PMC_STATUS_OK)
                        return (result);
                }
                else
                {
                    // y の値が 32bit では表現できない場合
                    __UNIT_TYPE y_bit_count = sizeof(y) * 8 - _LZCNT_ALT_32(y_hi);
                    if (x_bit_count < y_bit_count)
                    {
                        // 演算結果は負となってしまうのでエラーを返す。
                        return (PMC_STATUS_OUT_OF_RANGE);
                    }
                    __UNIT_TYPE z_bit_count = x_bit_count;
                    __UNIT_TYPE nz_light_check_code;
                    if ((result = AllocateNumber(&nz, z_bit_count, &nz_light_check_code)) != PMC_STATUS_OK)
                        return (result);
                    if ((result = Subtruct_X_2W(nx, y_hi, y_lo, nz)) != PMC_STATUS_OK)
                    {
                        DeallocateNumber(nz);
                        return (result == PMC_STATUS_INTERNAL_BORROW ? PMC_STATUS_OUT_OF_RANGE : result);
                    }
                    if ((result = CheckBlockLight(nz->BLOCK, nz_light_check_code)) != PMC_STATUS_OK)
                        return (result);
                }
            }
            else
            {
                // _UINT64_T が 1 ワードで表現できる場合

                __UNIT_TYPE x_bit_count = nx->UNIT_BIT_COUNT;
                __UNIT_TYPE y_bit_count = sizeof(y) * 8 - _LZCNT_ALT_UNIT((__UNIT_TYPE)y);
                if (x_bit_count < y_bit_count)
                {
                    // 演算結果は負となってしまうのでエラーを返す。
                    return (PMC_STATUS_OUT_OF_RANGE);
                }
                __UNIT_TYPE z_bit_count = x_bit_count;
                __UNIT_TYPE nz_light_check_code;
                if ((result = AllocateNumber(&nz, z_bit_count, &nz_light_check_code)) != PMC_STATUS_OK)
                    return (result);
                if ((result = Subtruct_X_1W(nx, (__UNIT_TYPE)y, nz)) != PMC_STATUS_OK)
                {
                    DeallocateNumber(nz);
                    return (result == PMC_STATUS_INTERNAL_BORROW ? PMC_STATUS_OUT_OF_RANGE : result);
                }
                if ((result = CheckBlockLight(nz->BLOCK, nz_light_check_code)) != PMC_STATUS_OK)
                    return (result);
            }
            CommitNumber(nz);
            if (nz->IS_ZERO)
            {
                DeallocateNumber(nz);
                nz = &number_zero;
            }
        }
        *o = nz;
    }
#ifdef _DEBUG
    if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
        return (result);
#endif
    return (PMC_STATUS_OK);
}

PMC_STATUS_CODE __PMC_CALL PMC_Subtruct_X_X(HANDLE x, HANDLE y, HANDLE* o)
{
    if (x == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    if (y == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    if (o == NULL)
        return (PMC_STATUS_ARGUMENT_ERROR);
    NUMBER_HEADER* nx = (NUMBER_HEADER*)x;
    NUMBER_HEADER* ny = (NUMBER_HEADER*)y;
    PMC_STATUS_CODE result;
    if ((result = CheckNumber(nx)) != PMC_STATUS_OK)
        return (result);
    if ((result = CheckNumber(ny)) != PMC_STATUS_OK)
        return (result);
    NUMBER_HEADER* nz;
    if (nx->IS_ZERO)
    {
        if (ny->IS_ZERO)
        {
            // y がゼロである場合

            // x と y がともにゼロであるので、演算結果のゼロを呼び出し元に返す。
            *o = &number_zero;
        }
        else
        {
            // y がゼロではない場合

            // 演算結果は負となってしまうのでエラーを返す。
            return (PMC_STATUS_OUT_OF_RANGE);
        }
    }
    else
    {
        // x がゼロではない場合

        if (ny->IS_ZERO)
        {
            // y がゼロである場合

            // 演算結果となる x の値を持つ NUMBER_HEADER 構造体を獲得し、呼び出し元へ返す。
            if ((result = DuplicateNumber(nx, &nz)) != PMC_STATUS_OK)
                return (result);
        }
        else
        {
            // x と y がともにゼロではない場合

            // x と y の差を計算する
            __UNIT_TYPE x_bit_count = nx->UNIT_BIT_COUNT;
            __UNIT_TYPE y_bit_count = ny->UNIT_BIT_COUNT;
            if (x_bit_count < y_bit_count)
            {
                // 演算結果は負となってしまうのでエラーを返す。
                return (PMC_STATUS_OUT_OF_RANGE);
            }
            __UNIT_TYPE z_bit_count = x_bit_count;
            __UNIT_TYPE nz_light_check_code;
            if ((result = AllocateNumber(&nz, z_bit_count, &nz_light_check_code)) != PMC_STATUS_OK)
                return (result);
            if ((result = Subtruct_X_X(nx, ny, nz)) != PMC_STATUS_OK)
            {
                DeallocateNumber(nz);
                return (result == PMC_STATUS_INTERNAL_BORROW ? PMC_STATUS_OUT_OF_RANGE : result);
            }
            if ((result = CheckBlockLight(nz->BLOCK, nz_light_check_code)) != PMC_STATUS_OK)
                return (result);
            CommitNumber(nz);
        }
        *o = nz;
    }
#ifdef _DEBUG
    if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
        return (result);
#endif
    return (PMC_STATUS_OK);
}

PMC_STATUS_CODE Initialize_Subtruct(PROCESSOR_FEATURES* feature)
{
    return (PMC_STATUS_OK);
}


/*
 * END OF FILE
 */