; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

	TITLE	Z:\Sources\Lunor\Repos\rougemeilland\Palmtree.Math.Core.Implements\Palmtree.Math.Core.Implements\TEST_op_DivRem.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__7B7A869E_ctype@h DB 01H
__457DD326_basetsd@h DB 01H
__4384A2D9_corecrt_memcpy_s@h DB 01H
__4E51A221_corecrt_wstring@h DB 01H
__2140C079_string@h DB 01H
__1887E595_winnt@h DB 01H
__9FC7C64B_processthreadsapi@h DB 01H
__FA470AEC_memoryapi@h DB 01H
__F37DAFF1_winerror@h DB 01H
__7A450CCC_winbase@h DB 01H
__B4B40122_winioctl@h DB 01H
__86261D59_stralign@h DB 01H
__1C66ECB2_pmc_debug@h DB 01H
__E0086EBB_test_op_divrem@c DB 01H
msvcjmc	ENDS
PUBLIC	_TEST_PMC_DivRem_I_X
PUBLIC	_TEST_PMC_DivRem_L_X
PUBLIC	_TEST_PMC_DivRem_X_I
PUBLIC	_TEST_PMC_DivRem_X_L
PUBLIC	_TEST_PMC_DivRem_X_X
PUBLIC	__JustMyCode_Default
EXTRN	_TEST_Assert:PROC
EXTRN	_FormatTestLabel:PROC
EXTRN	_FormatTestMesssage:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
_DATA	SEGMENT
$SG94509 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94510 DB	'PMC_DivRem_I_X (%d.%d)', 00H
	ORG $+1
$SG94511 DB	'PMC_DivRem_I_X', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+3
$SG94512 DB	'PMC_DivRem_I_X (%d.%d)', 00H
	ORG $+1
$SG94514 DB	08fH, 0a4H, 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H, 0eaH
	DB	092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+1
$SG94515 DB	'PMC_DivRem_I_X (%d.%d)', 00H
	ORG $+1
$SG94516 DB	08fH, 0e8H, 097H, ']', 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H
	DB	0eaH, 092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+3
$SG94517 DB	'PMC_DivRem_I_X (%d.%d)', 00H
	ORG $+1
$SG94543 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94544 DB	'PMC_DivRem_L_X (%d.%d)', 00H
	ORG $+1
$SG94545 DB	'PMC_DivRem_L_X', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+3
$SG94546 DB	'PMC_DivRem_L_X (%d.%d)', 00H
	ORG $+1
$SG94548 DB	08fH, 0a4H, 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H, 0eaH
	DB	092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+1
$SG94549 DB	'PMC_DivRem_L_X (%d.%d)', 00H
	ORG $+1
$SG94550 DB	08fH, 0e8H, 097H, ']', 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H
	DB	0eaH, 092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+3
$SG94551 DB	'PMC_DivRem_L_X (%d.%d)', 00H
	ORG $+1
$SG94582 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94583 DB	'PMC_DivRem_X_I (%d.%d)', 00H
	ORG $+1
$SG94584 DB	'PMC_DivRem_X_I', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+3
$SG94585 DB	'PMC_DivRem_X_I (%d.%d)', 00H
	ORG $+1
$SG94587 DB	'PMC_ToByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+2
$SG94588 DB	'PMC_DivRem_X_I (%d.%d)', 00H
	ORG $+1
$SG94589 DB	08fH, 0a4H, 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H, 0eaH
	DB	092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+1
$SG94590 DB	'PMC_DivRem_X_I (%d.%d)', 00H
	ORG $+1
$SG94591 DB	08fH, 0e8H, 097H, ']', 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H
	DB	0eaH, 092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+3
$SG94592 DB	'PMC_DivRem_X_I (%d.%d)', 00H
	ORG $+1
$SG94624 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94625 DB	'PMC_DivRem_X_L (%d.%d)', 00H
	ORG $+1
$SG94626 DB	'PMC_DivRem_X_L', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+3
$SG94627 DB	'PMC_DivRem_X_L (%d.%d)', 00H
	ORG $+1
$SG94629 DB	'PMC_ToByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+2
$SG94630 DB	'PMC_DivRem_X_L (%d.%d)', 00H
	ORG $+1
$SG94631 DB	08fH, 0a4H, 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H, 0eaH
	DB	092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+1
$SG94632 DB	'PMC_DivRem_X_L (%d.%d)', 00H
	ORG $+1
$SG94633 DB	08fH, 0e8H, 097H, ']', 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H
	DB	0eaH, 092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+3
$SG94634 DB	'PMC_DivRem_X_L (%d.%d)', 00H
	ORG $+1
$SG94674 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94675 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94676 DB	'PMC_FromByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
$SG94677 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94678 DB	'PMC_DivRem_X_X', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+3
$SG94679 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94681 DB	'PMC_ToByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+2
$SG94682 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94683 DB	'PMC_ToByteArray', 082H, 0ccH, 095H, 09cH, 08bH, 'A', 083H
	DB	'R', 081H, '[', 083H, 'h', 082H, 0aaH, 08aH, 0faH, 091H, 0d2H, 092H
	DB	0caH, 082H, 0e8H, 082H, 0c5H, 082H, 0cdH, 082H, 0c8H, 082H, 0a2H
	DB	'(%d)', 00H
	ORG $+2
$SG94684 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94685 DB	08fH, 0a4H, 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H, 0eaH
	DB	092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+1
$SG94686 DB	'PMC_DivRem_X_X (%d.%d)', 00H
	ORG $+1
$SG94687 DB	08fH, 0e8H, 097H, ']', 082H, 0ccH, 092H, 'l', 082H, 0aaH, 088H
	DB	0eaH, 092H, 'v', 082H, 0b5H, 082H, 0c8H, 082H, 0a2H, 00H
	ORG $+3
$SG94688 DB	'PMC_DivRem_X_X (%d.%d)', 00H
_DATA	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\pmc_debug.h
_TEXT	SEGMENT
_buffer1$ = 8						; size = 4
_count1$ = 12						; size = 4
_buffer2$ = 16						; size = 4
_count2$ = 20						; size = 4
__EQUALS_MEMORY PROC

; 153  : {

	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __1C66ECB2_pmc_debug@h
	call	@__CheckForDebuggerJustMyCode@4

; 154  :     if (count1 != count2)

	mov	eax, DWORD PTR _count1$[ebp]
	cmp	eax, DWORD PTR _count2$[ebp]
	je	SHORT $LN2@EQUALS_MEM

; 155  :         return (-1);

	or	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN2@EQUALS_MEM:

; 156  :     while (count1 > 0)

	cmp	DWORD PTR _count1$[ebp], 0
	jbe	SHORT $LN3@EQUALS_MEM

; 157  :     {
; 158  :         if (*buffer1 != *buffer2)

	mov	ecx, DWORD PTR _buffer1$[ebp]
	movzx	edx, BYTE PTR [ecx]
	mov	eax, DWORD PTR _buffer2$[ebp]
	movzx	ecx, BYTE PTR [eax]
	cmp	edx, ecx
	je	SHORT $LN5@EQUALS_MEM

; 159  :             return (-1);

	or	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN5@EQUALS_MEM:

; 160  :         ++buffer1;

	mov	edx, DWORD PTR _buffer1$[ebp]
	add	edx, 1
	mov	DWORD PTR _buffer1$[ebp], edx

; 161  :         ++buffer2;

	mov	eax, DWORD PTR _buffer2$[ebp]
	add	eax, 1
	mov	DWORD PTR _buffer2$[ebp], eax

; 162  :         --count1;

	mov	ecx, DWORD PTR _count1$[ebp]
	sub	ecx, 1
	mov	DWORD PTR _count1$[ebp], ecx

; 163  :     }

	jmp	SHORT $LN2@EQUALS_MEM
$LN3@EQUALS_MEM:

; 164  :     return (0);

	xor	eax, eax
$LN1@EQUALS_MEM:

; 165  : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
__EQUALS_MEMORY ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\test_op_divrem.c
_TEXT	SEGMENT
tv212 = -648						; size = 4
tv197 = -644						; size = 4
tv182 = -640						; size = 4
tv163 = -636						; size = 4
tv143 = -632						; size = 4
tv92 = -628						; size = 4
tv74 = -624						; size = 4
_q_r_result$ = -620					; size = 4
_v_result$ = -616					; size = 4
_u_result$ = -612					; size = 4
_result$ = -608						; size = 4
_actual_r_buf_size$ = -600				; size = 4
_actual_r_buf$ = -588					; size = 256
_actual_q_buf_size$ = -324				; size = 4
_actual_q_buf$ = -312					; size = 256
_r$ = -48						; size = 4
_q$ = -36						; size = 4
_v$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_return_code$ = 36				; size = 4
_desired_q_buf$ = 40					; size = 4
_desired_q_buf_size$ = 44				; size = 4
_desired_r_buf$ = 48					; size = 4
_desired_r_buf_size$ = 52				; size = 4
_TEST_PMC_DivRem_X_X PROC

; 124  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 648				; 00000288H
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-648]
	mov	ecx, 162				; 000000a2H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __E0086EBB_test_op_divrem@c
	call	@__CheckForDebuggerJustMyCode@4

; 125  : 	HANDLE u;
; 126  : 	HANDLE v;
; 127  : 	HANDLE q;
; 128  : 	HANDLE r;
; 129  : 	unsigned char actual_q_buf[256];
; 130  : 	size_t actual_q_buf_size;
; 131  : 	unsigned char actual_r_buf[256];
; 132  : 	size_t actual_r_buf_size;
; 133  : 	PMC_STATUS_CODE result;
; 134  : 	PMC_STATUS_CODE u_result;
; 135  : 	PMC_STATUS_CODE v_result;
; 136  : 	PMC_STATUS_CODE q_r_result;
; 137  : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 1), (u_result = ep->PMC_FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN7@TEST_PMC_D
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN8@TEST_PMC_D
$LN7@TEST_PMC_D:
	mov	DWORD PTR tv74[ebp], 0
$LN8@TEST_PMC_D:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET $SG94674
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94675
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 138  : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 2), (v_result = ep->PMC_FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN9@TEST_PMC_D
	mov	DWORD PTR tv92[ebp], 1
	jmp	SHORT $LN10@TEST_PMC_D
$LN9@TEST_PMC_D:
	mov	DWORD PTR tv92[ebp], 0
$LN10@TEST_PMC_D:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET $SG94676
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv92[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94677
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 139  : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 3), (q_r_result = ep->PMC_DivRem_X_X(u, v, &q, &r)) == desired_return_code, FormatTestMesssage("PMC_DivRem_X_Xの復帰コードが期待通りではない(%d)", q_r_result));

	mov	esi, esp
	lea	eax, DWORD PTR _r$[ebp]
	push	eax
	lea	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+120]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _q_r_result$[ebp], eax
	mov	eax, DWORD PTR _q_r_result$[ebp]
	cmp	eax, DWORD PTR _desired_return_code$[ebp]
	jne	SHORT $LN11@TEST_PMC_D
	mov	DWORD PTR tv143[ebp], 1
	jmp	SHORT $LN12@TEST_PMC_D
$LN11@TEST_PMC_D:
	mov	DWORD PTR tv143[ebp], 0
$LN12@TEST_PMC_D:
	mov	ecx, DWORD PTR _q_r_result$[ebp]
	push	ecx
	push	OFFSET $SG94678
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv143[ebp]
	push	edx
	push	3
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94679
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 140  : 	if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR _desired_return_code$[ebp], 0
	jne	$LN2@TEST_PMC_D

; 141  : 	{
; 142  : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 4), (result = ep->PMC_ToByteArray(q, actual_q_buf, sizeof(actual_q_buf), &actual_q_buf_size)) == PMC_STATUS_OK, FormatTestMesssage("PMC_ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	edx, DWORD PTR _actual_q_buf_size$[ebp]
	push	edx
	push	256					; 00000100H
	lea	eax, DWORD PTR _actual_q_buf$[ebp]
	push	eax
	mov	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+24]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN13@TEST_PMC_D
	mov	DWORD PTR tv163[ebp], 1
	jmp	SHORT $LN14@TEST_PMC_D
$LN13@TEST_PMC_D:
	mov	DWORD PTR tv163[ebp], 0
$LN14@TEST_PMC_D:
	mov	ecx, DWORD PTR _result$[ebp]
	push	ecx
	push	OFFSET $SG94681
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv163[ebp]
	push	edx
	push	4
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94682
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 143  : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 5), (result = ep->PMC_ToByteArray(r, actual_r_buf, sizeof(actual_r_buf), &actual_r_buf_size)) == PMC_STATUS_OK, FormatTestMesssage("PMC_ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	edx, DWORD PTR _actual_r_buf_size$[ebp]
	push	edx
	push	256					; 00000100H
	lea	eax, DWORD PTR _actual_r_buf$[ebp]
	push	eax
	mov	ecx, DWORD PTR _r$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+24]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN15@TEST_PMC_D
	mov	DWORD PTR tv182[ebp], 1
	jmp	SHORT $LN16@TEST_PMC_D
$LN15@TEST_PMC_D:
	mov	DWORD PTR tv182[ebp], 0
$LN16@TEST_PMC_D:
	mov	ecx, DWORD PTR _result$[ebp]
	push	ecx
	push	OFFSET $SG94683
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv182[ebp]
	push	edx
	push	5
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94684
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 144  : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 6), _EQUALS_MEMORY(actual_q_buf, actual_q_buf_size, desired_q_buf, desired_q_buf_size) == 0, "商の値が一致しない");

	mov	edx, DWORD PTR _desired_q_buf_size$[ebp]
	push	edx
	mov	eax, DWORD PTR _desired_q_buf$[ebp]
	push	eax
	mov	ecx, DWORD PTR _actual_q_buf_size$[ebp]
	push	ecx
	lea	edx, DWORD PTR _actual_q_buf$[ebp]
	push	edx
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN17@TEST_PMC_D
	mov	DWORD PTR tv197[ebp], 1
	jmp	SHORT $LN18@TEST_PMC_D
$LN17@TEST_PMC_D:
	mov	DWORD PTR tv197[ebp], 0
$LN18@TEST_PMC_D:
	push	OFFSET $SG94685
	mov	eax, DWORD PTR tv197[ebp]
	push	eax
	push	6
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94686
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 145  : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_X (%d.%d)", no, 7), _EQUALS_MEMORY(actual_r_buf, actual_r_buf_size, desired_r_buf, desired_r_buf_size) == 0, "剰余の値が一致しない");

	mov	eax, DWORD PTR _desired_r_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_r_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_r_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_r_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN19@TEST_PMC_D
	mov	DWORD PTR tv212[ebp], 1
	jmp	SHORT $LN20@TEST_PMC_D
$LN19@TEST_PMC_D:
	mov	DWORD PTR tv212[ebp], 0
$LN20@TEST_PMC_D:
	push	OFFSET $SG94687
	mov	ecx, DWORD PTR tv212[ebp]
	push	ecx
	push	7
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET $SG94688
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H
$LN2@TEST_PMC_D:

; 146  : 	}
; 147  : 	if (q_r_result == PMC_STATUS_OK)

	cmp	DWORD PTR _q_r_result$[ebp], 0
	jne	SHORT $LN3@TEST_PMC_D

; 148  : 	{
; 149  : 		ep->PMC_Dispose(q);

	mov	esi, esp
	mov	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp

; 150  : 		ep->PMC_Dispose(r);

	mov	esi, esp
	mov	ecx, DWORD PTR _r$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_PMC_D:

; 151  : 	}
; 152  : 	if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN4@TEST_PMC_D

; 153  : 		ep->PMC_Dispose(v);

	mov	esi, esp
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN4@TEST_PMC_D:

; 154  : 	if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_PMC_D

; 155  : 		ep->PMC_Dispose(u);

	mov	esi, esp
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_PMC_D:

; 156  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN30@TEST_PMC_D
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 648				; 00000288H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN30@TEST_PMC_D:
	DD	8
	DD	$LN29@TEST_PMC_D
$LN29@TEST_PMC_D:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN21@TEST_PMC_D
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN22@TEST_PMC_D
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN23@TEST_PMC_D
	DD	-48					; ffffffd0H
	DD	4
	DD	$LN24@TEST_PMC_D
	DD	-312					; fffffec8H
	DD	256					; 00000100H
	DD	$LN25@TEST_PMC_D
	DD	-324					; fffffebcH
	DD	4
	DD	$LN26@TEST_PMC_D
	DD	-588					; fffffdb4H
	DD	256					; 00000100H
	DD	$LN27@TEST_PMC_D
	DD	-600					; fffffda8H
	DD	4
	DD	$LN28@TEST_PMC_D
$LN28@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN27@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN26@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN25@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN24@TEST_PMC_D:
	DB	114					; 00000072H
	DB	0
$LN23@TEST_PMC_D:
	DB	113					; 00000071H
	DB	0
$LN22@TEST_PMC_D:
	DB	118					; 00000076H
	DB	0
$LN21@TEST_PMC_D:
	DB	117					; 00000075H
	DB	0
_TEST_PMC_DivRem_X_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\test_op_divrem.c
_TEXT	SEGMENT
tv170 = -352						; size = 4
tv160 = -348						; size = 4
tv145 = -344						; size = 4
tv93 = -340						; size = 4
tv74 = -336						; size = 4
_q_result$ = -332					; size = 4
_u_result$ = -328					; size = 4
_result$ = -324						; size = 4
_actual_r$ = -316					; size = 8
_actual_q_buf_size$ = -300				; size = 4
_actual_q_buf$ = -288					; size = 256
_q$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v$ = 28						; size = 8
_desired_return_code$ = 36				; size = 4
_desired_q_buf$ = 40					; size = 4
_desired_q_buf_size$ = 44				; size = 4
_desired_r$ = 48					; size = 8
_TEST_PMC_DivRem_X_L PROC

; 100  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 352				; 00000160H
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-352]
	mov	ecx, 88					; 00000058H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __E0086EBB_test_op_divrem@c
	call	@__CheckForDebuggerJustMyCode@4

; 101  :     HANDLE u;
; 102  :     HANDLE q;
; 103  :     unsigned char actual_q_buf[256];
; 104  :     size_t actual_q_buf_size;
; 105  :     unsigned __int64 actual_r;
; 106  :     PMC_STATUS_CODE result;
; 107  :     PMC_STATUS_CODE u_result;
; 108  :     PMC_STATUS_CODE q_result;
; 109  :     TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_L (%d.%d)", no, 1), (u_result = ep->PMC_FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN6@TEST_PMC_D
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN7@TEST_PMC_D
$LN6@TEST_PMC_D:
	mov	DWORD PTR tv74[ebp], 0
$LN7@TEST_PMC_D:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET $SG94624
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94625
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 110  :     TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_L (%d.%d)", no, 2), (q_result = ep->PMC_DivRem_X_L(u, v, &q, &actual_r)) == desired_return_code, FormatTestMesssage("PMC_DivRem_X_Lの復帰コードが期待通りではない(%d)", q_result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_r$[ebp]
	push	eax
	lea	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+116]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _q_result$[ebp], eax
	mov	ecx, DWORD PTR _q_result$[ebp]
	cmp	ecx, DWORD PTR _desired_return_code$[ebp]
	jne	SHORT $LN8@TEST_PMC_D
	mov	DWORD PTR tv93[ebp], 1
	jmp	SHORT $LN9@TEST_PMC_D
$LN8@TEST_PMC_D:
	mov	DWORD PTR tv93[ebp], 0
$LN9@TEST_PMC_D:
	mov	edx, DWORD PTR _q_result$[ebp]
	push	edx
	push	OFFSET $SG94626
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv93[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94627
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 111  :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR _desired_return_code$[ebp], 0
	jne	$LN2@TEST_PMC_D

; 112  :     {
; 113  :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_L (%d.%d)", no, 3), (result = ep->PMC_ToByteArray(q, actual_q_buf, sizeof(actual_q_buf), &actual_q_buf_size)) == PMC_STATUS_OK, FormatTestMesssage("PMC_ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_q_buf_size$[ebp]
	push	eax
	push	256					; 00000100H
	lea	ecx, DWORD PTR _actual_q_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _q$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN10@TEST_PMC_D
	mov	DWORD PTR tv145[ebp], 1
	jmp	SHORT $LN11@TEST_PMC_D
$LN10@TEST_PMC_D:
	mov	DWORD PTR tv145[ebp], 0
$LN11@TEST_PMC_D:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET $SG94629
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv145[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94630
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 114  :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_L (%d.%d)", no, 4), _EQUALS_MEMORY(actual_q_buf, actual_q_buf_size, desired_q_buf, desired_q_buf_size) == 0, "商の値が一致しない");

	mov	eax, DWORD PTR _desired_q_buf_size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _desired_q_buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _actual_q_buf_size$[ebp]
	push	edx
	lea	eax, DWORD PTR _actual_q_buf$[ebp]
	push	eax
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN12@TEST_PMC_D
	mov	DWORD PTR tv160[ebp], 1
	jmp	SHORT $LN13@TEST_PMC_D
$LN12@TEST_PMC_D:
	mov	DWORD PTR tv160[ebp], 0
$LN13@TEST_PMC_D:
	push	OFFSET $SG94631
	mov	ecx, DWORD PTR tv160[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET $SG94632
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 115  :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_L (%d.%d)", no, 5), actual_r == desired_r, "剰余の値が一致しない");

	mov	ecx, DWORD PTR _actual_r$[ebp]
	cmp	ecx, DWORD PTR _desired_r$[ebp]
	jne	SHORT $LN14@TEST_PMC_D
	mov	edx, DWORD PTR _actual_r$[ebp+4]
	cmp	edx, DWORD PTR _desired_r$[ebp+4]
	jne	SHORT $LN14@TEST_PMC_D
	mov	DWORD PTR tv170[ebp], 1
	jmp	SHORT $LN15@TEST_PMC_D
$LN14@TEST_PMC_D:
	mov	DWORD PTR tv170[ebp], 0
$LN15@TEST_PMC_D:
	push	OFFSET $SG94633
	mov	eax, DWORD PTR tv170[ebp]
	push	eax
	push	5
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94634
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H
$LN2@TEST_PMC_D:

; 116  :     }
; 117  :     if (q_result == PMC_STATUS_OK)

	cmp	DWORD PTR _q_result$[ebp], 0
	jne	SHORT $LN3@TEST_PMC_D

; 118  :         ep->PMC_Dispose(q);

	mov	esi, esp
	mov	eax, DWORD PTR _q$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_PMC_D:

; 119  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_PMC_D

; 120  :         ep->PMC_Dispose(u);

	mov	esi, esp
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_PMC_D:

; 121  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN22@TEST_PMC_D
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 352				; 00000160H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN22@TEST_PMC_D:
	DD	5
	DD	$LN21@TEST_PMC_D
$LN21@TEST_PMC_D:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN16@TEST_PMC_D
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN17@TEST_PMC_D
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN18@TEST_PMC_D
	DD	-300					; fffffed4H
	DD	4
	DD	$LN19@TEST_PMC_D
	DD	-316					; fffffec4H
	DD	8
	DD	$LN20@TEST_PMC_D
$LN20@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	0
$LN19@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN18@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN17@TEST_PMC_D:
	DB	113					; 00000071H
	DB	0
$LN16@TEST_PMC_D:
	DB	117					; 00000075H
	DB	0
_TEST_PMC_DivRem_X_L ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\test_op_divrem.c
_TEXT	SEGMENT
tv170 = -348						; size = 4
tv160 = -344						; size = 4
tv145 = -340						; size = 4
tv93 = -336						; size = 4
tv74 = -332						; size = 4
_q_result$ = -328					; size = 4
_u_result$ = -324					; size = 4
_result$ = -320						; size = 4
_actual_r$ = -312					; size = 4
_actual_q_buf_size$ = -300				; size = 4
_actual_q_buf$ = -288					; size = 256
_q$ = -24						; size = 4
_u$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u_buf$ = 20						; size = 4
_u_buf_size$ = 24					; size = 4
_v$ = 28						; size = 4
_desired_return_code$ = 32				; size = 4
_desired_q_buf$ = 36					; size = 4
_desired_q_buf_size$ = 40				; size = 4
_desired_r$ = 44					; size = 4
_TEST_PMC_DivRem_X_I PROC

; 76   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 348				; 0000015cH
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-348]
	mov	ecx, 87					; 00000057H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __E0086EBB_test_op_divrem@c
	call	@__CheckForDebuggerJustMyCode@4

; 77   :     HANDLE u;
; 78   :     HANDLE q;
; 79   :     unsigned char actual_q_buf[256];
; 80   :     size_t actual_q_buf_size;
; 81   :     unsigned __int32 actual_r;
; 82   :     PMC_STATUS_CODE result;
; 83   :     PMC_STATUS_CODE u_result;
; 84   :     PMC_STATUS_CODE q_result;
; 85   :     TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_I (%d.%d)", no, 1), (u_result = ep->PMC_FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	mov	esi, esp
	lea	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _u_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _u_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _u_result$[ebp], eax
	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN6@TEST_PMC_D
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN7@TEST_PMC_D
$LN6@TEST_PMC_D:
	mov	DWORD PTR tv74[ebp], 0
$LN7@TEST_PMC_D:
	mov	edx, DWORD PTR _u_result$[ebp]
	push	edx
	push	OFFSET $SG94582
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94583
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 86   :     TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_I (%d.%d)", no, 2), (q_result = ep->PMC_DivRem_X_I(u, v, &q, &actual_r)) == desired_return_code, FormatTestMesssage("PMC_DivRem_X_Iの復帰コードが期待通りではない(%d)", q_result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_r$[ebp]
	push	eax
	lea	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+112]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _q_result$[ebp], eax
	mov	eax, DWORD PTR _q_result$[ebp]
	cmp	eax, DWORD PTR _desired_return_code$[ebp]
	jne	SHORT $LN8@TEST_PMC_D
	mov	DWORD PTR tv93[ebp], 1
	jmp	SHORT $LN9@TEST_PMC_D
$LN8@TEST_PMC_D:
	mov	DWORD PTR tv93[ebp], 0
$LN9@TEST_PMC_D:
	mov	ecx, DWORD PTR _q_result$[ebp]
	push	ecx
	push	OFFSET $SG94584
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv93[ebp]
	push	edx
	push	2
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94585
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 87   :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR _desired_return_code$[ebp], 0
	jne	$LN2@TEST_PMC_D

; 88   :     {
; 89   :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_I (%d.%d)", no, 3), (result = ep->PMC_ToByteArray(q, actual_q_buf, sizeof(actual_q_buf), &actual_q_buf_size)) == PMC_STATUS_OK, FormatTestMesssage("PMC_ToByteArrayの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	edx, DWORD PTR _actual_q_buf_size$[ebp]
	push	edx
	push	256					; 00000100H
	lea	eax, DWORD PTR _actual_q_buf$[ebp]
	push	eax
	mov	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+24]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN10@TEST_PMC_D
	mov	DWORD PTR tv145[ebp], 1
	jmp	SHORT $LN11@TEST_PMC_D
$LN10@TEST_PMC_D:
	mov	DWORD PTR tv145[ebp], 0
$LN11@TEST_PMC_D:
	mov	ecx, DWORD PTR _result$[ebp]
	push	ecx
	push	OFFSET $SG94587
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv145[ebp]
	push	edx
	push	3
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94588
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 90   :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_I (%d.%d)", no, 4), _EQUALS_MEMORY(actual_q_buf, actual_q_buf_size, desired_q_buf, desired_q_buf_size) == 0, "商の値が一致しない");

	mov	edx, DWORD PTR _desired_q_buf_size$[ebp]
	push	edx
	mov	eax, DWORD PTR _desired_q_buf$[ebp]
	push	eax
	mov	ecx, DWORD PTR _actual_q_buf_size$[ebp]
	push	ecx
	lea	edx, DWORD PTR _actual_q_buf$[ebp]
	push	edx
	call	__EQUALS_MEMORY
	add	esp, 16					; 00000010H
	test	eax, eax
	jne	SHORT $LN12@TEST_PMC_D
	mov	DWORD PTR tv160[ebp], 1
	jmp	SHORT $LN13@TEST_PMC_D
$LN12@TEST_PMC_D:
	mov	DWORD PTR tv160[ebp], 0
$LN13@TEST_PMC_D:
	push	OFFSET $SG94589
	mov	eax, DWORD PTR tv160[ebp]
	push	eax
	push	4
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94590
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 91   :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_X_I (%d.%d)", no, 5), actual_r == desired_r, "剰余の値が一致しない");

	mov	eax, DWORD PTR _actual_r$[ebp]
	cmp	eax, DWORD PTR _desired_r$[ebp]
	jne	SHORT $LN14@TEST_PMC_D
	mov	DWORD PTR tv170[ebp], 1
	jmp	SHORT $LN15@TEST_PMC_D
$LN14@TEST_PMC_D:
	mov	DWORD PTR tv170[ebp], 0
$LN15@TEST_PMC_D:
	push	OFFSET $SG94591
	mov	ecx, DWORD PTR tv170[ebp]
	push	ecx
	push	5
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET $SG94592
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H
$LN2@TEST_PMC_D:

; 92   :     }
; 93   :     if (q_result == PMC_STATUS_OK)

	cmp	DWORD PTR _q_result$[ebp], 0
	jne	SHORT $LN3@TEST_PMC_D

; 94   :         ep->PMC_Dispose(q);

	mov	esi, esp
	mov	ecx, DWORD PTR _q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@TEST_PMC_D:

; 95   :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR _u_result$[ebp], 0
	jne	SHORT $LN1@TEST_PMC_D

; 96   :         ep->PMC_Dispose(u);

	mov	esi, esp
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_PMC_D:

; 97   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN22@TEST_PMC_D
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 348				; 0000015cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN22@TEST_PMC_D:
	DD	5
	DD	$LN21@TEST_PMC_D
$LN21@TEST_PMC_D:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN16@TEST_PMC_D
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN17@TEST_PMC_D
	DD	-288					; fffffee0H
	DD	256					; 00000100H
	DD	$LN18@TEST_PMC_D
	DD	-300					; fffffed4H
	DD	4
	DD	$LN19@TEST_PMC_D
	DD	-312					; fffffec8H
	DD	4
	DD	$LN20@TEST_PMC_D
$LN20@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	0
$LN19@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	95					; 0000005fH
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN18@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	95					; 0000005fH
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	0
$LN17@TEST_PMC_D:
	DB	113					; 00000071H
	DB	0
$LN16@TEST_PMC_D:
	DB	117					; 00000075H
	DB	0
_TEST_PMC_DivRem_X_I ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\test_op_divrem.c
_TEXT	SEGMENT
tv146 = -68						; size = 4
tv136 = -64						; size = 4
tv93 = -60						; size = 4
tv74 = -56						; size = 4
_v_result$ = -52					; size = 4
_result$ = -48						; size = 4
_actual_r$ = -40					; size = 8
_actual_q$ = -24					; size = 8
_v$ = -8						; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u$ = 20						; size = 8
_v_buf$ = 28						; size = 4
_v_buf_size$ = 32					; size = 4
_desired_return_code$ = 36				; size = 4
_desired_q$ = 40					; size = 8
_desired_r$ = 48					; size = 8
_TEST_PMC_DivRem_L_X PROC

; 58   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-68]
	mov	ecx, 17					; 00000011H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __E0086EBB_test_op_divrem@c
	call	@__CheckForDebuggerJustMyCode@4

; 59   : 	HANDLE v;
; 60   : 	unsigned __int64 actual_q;
; 61   :     unsigned __int64 actual_r;
; 62   :     PMC_STATUS_CODE result;
; 63   : 	PMC_STATUS_CODE v_result;
; 64   : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_L_X (%d.%d)", no, 1), (v_result = ep->PMC_FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN5@TEST_PMC_D
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_PMC_D
$LN5@TEST_PMC_D:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_PMC_D:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET $SG94543
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94544
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 65   : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_L_X (%d.%d)", no, 2), (result = ep->PMC_DivRem_L_X(u, v, &actual_q, &actual_r)) == desired_return_code, FormatTestMesssage("PMC_DivRem_L_Xの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_r$[ebp]
	push	eax
	lea	ecx, DWORD PTR _actual_q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp+4]
	push	eax
	mov	ecx, DWORD PTR _u$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+108]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	mov	ecx, DWORD PTR _result$[ebp]
	cmp	ecx, DWORD PTR _desired_return_code$[ebp]
	jne	SHORT $LN7@TEST_PMC_D
	mov	DWORD PTR tv93[ebp], 1
	jmp	SHORT $LN8@TEST_PMC_D
$LN7@TEST_PMC_D:
	mov	DWORD PTR tv93[ebp], 0
$LN8@TEST_PMC_D:
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	push	OFFSET $SG94545
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv93[ebp]
	push	eax
	push	2
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94546
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 66   : 	if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR _desired_return_code$[ebp], 0
	jne	$LN2@TEST_PMC_D

; 67   : 	{
; 68   : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_L_X (%d.%d)", no, 3), actual_q == desired_q, "商の値が一致しない");

	mov	eax, DWORD PTR _actual_q$[ebp]
	cmp	eax, DWORD PTR _desired_q$[ebp]
	jne	SHORT $LN9@TEST_PMC_D
	mov	ecx, DWORD PTR _actual_q$[ebp+4]
	cmp	ecx, DWORD PTR _desired_q$[ebp+4]
	jne	SHORT $LN9@TEST_PMC_D
	mov	DWORD PTR tv136[ebp], 1
	jmp	SHORT $LN10@TEST_PMC_D
$LN9@TEST_PMC_D:
	mov	DWORD PTR tv136[ebp], 0
$LN10@TEST_PMC_D:
	push	OFFSET $SG94548
	mov	edx, DWORD PTR tv136[ebp]
	push	edx
	push	3
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94549
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 69   :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_L_X (%d.%d)", no, 4), actual_r == desired_r, "剰余の値が一致しない");

	mov	edx, DWORD PTR _actual_r$[ebp]
	cmp	edx, DWORD PTR _desired_r$[ebp]
	jne	SHORT $LN11@TEST_PMC_D
	mov	eax, DWORD PTR _actual_r$[ebp+4]
	cmp	eax, DWORD PTR _desired_r$[ebp+4]
	jne	SHORT $LN11@TEST_PMC_D
	mov	DWORD PTR tv146[ebp], 1
	jmp	SHORT $LN12@TEST_PMC_D
$LN11@TEST_PMC_D:
	mov	DWORD PTR tv146[ebp], 0
$LN12@TEST_PMC_D:
	push	OFFSET $SG94550
	mov	ecx, DWORD PTR tv146[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET $SG94551
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H
$LN2@TEST_PMC_D:

; 70   :     }
; 71   : 	if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN1@TEST_PMC_D

; 72   : 		ep->PMC_Dispose(v);

	mov	esi, esp
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_PMC_D:

; 73   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN17@TEST_PMC_D
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	add	esp, 68					; 00000044H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN17@TEST_PMC_D:
	DD	3
	DD	$LN16@TEST_PMC_D
$LN16@TEST_PMC_D:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN13@TEST_PMC_D
	DD	-24					; ffffffe8H
	DD	8
	DD	$LN14@TEST_PMC_D
	DD	-40					; ffffffd8H
	DD	8
	DD	$LN15@TEST_PMC_D
$LN15@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	0
$LN14@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	0
$LN13@TEST_PMC_D:
	DB	118					; 00000076H
	DB	0
_TEST_PMC_DivRem_L_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.implements\palmtree.math.core.implements\test_op_divrem.c
_TEXT	SEGMENT
tv146 = -60						; size = 4
tv136 = -56						; size = 4
tv93 = -52						; size = 4
tv74 = -48						; size = 4
_v_result$ = -44					; size = 4
_result$ = -40						; size = 4
_actual_r$ = -32					; size = 4
_actual_q$ = -20					; size = 4
_v$ = -8						; size = 4
_env$ = 8						; size = 4
_ep$ = 12						; size = 4
_no$ = 16						; size = 4
_u$ = 20						; size = 4
_v_buf$ = 24						; size = 4
_v_buf_size$ = 28					; size = 4
_desired_return_code$ = 32				; size = 4
_desired_q$ = 36					; size = 4
_desired_r$ = 40					; size = 4
_TEST_PMC_DivRem_I_X PROC

; 40   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-60]
	mov	ecx, 15					; 0000000fH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __E0086EBB_test_op_divrem@c
	call	@__CheckForDebuggerJustMyCode@4

; 41   : 	HANDLE v;
; 42   : 	unsigned __int32 actual_q;
; 43   :     unsigned __int32 actual_r;
; 44   :     PMC_STATUS_CODE result;
; 45   : 	PMC_STATUS_CODE v_result;
; 46   : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_I_X (%d.%d)", no, 1), (v_result = ep->PMC_FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage("PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	mov	esi, esp
	lea	eax, DWORD PTR _v$[ebp]
	push	eax
	mov	ecx, DWORD PTR _v_buf_size$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v_buf$[ebp]
	push	edx
	mov	eax, DWORD PTR _ep$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	call	ecx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _v_result$[ebp], eax
	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN5@TEST_PMC_D
	mov	DWORD PTR tv74[ebp], 1
	jmp	SHORT $LN6@TEST_PMC_D
$LN5@TEST_PMC_D:
	mov	DWORD PTR tv74[ebp], 0
$LN6@TEST_PMC_D:
	mov	edx, DWORD PTR _v_result$[ebp]
	push	edx
	push	OFFSET $SG94509
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR tv74[ebp]
	push	eax
	push	1
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94510
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 47   : 	TEST_Assert(env, FormatTestLabel("PMC_DivRem_I_X (%d.%d)", no, 2), (result = ep->PMC_DivRem_I_X(u, v, &actual_q, &actual_r)) == desired_return_code, FormatTestMesssage("PMC_DivRem_I_Xの復帰コードが期待通りではない(%d)", result));

	mov	esi, esp
	lea	eax, DWORD PTR _actual_r$[ebp]
	push	eax
	lea	ecx, DWORD PTR _actual_q$[ebp]
	push	ecx
	mov	edx, DWORD PTR _v$[ebp]
	push	edx
	mov	eax, DWORD PTR _u$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ep$[ebp]
	mov	edx, DWORD PTR [ecx+104]
	call	edx
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _result$[ebp], eax
	mov	eax, DWORD PTR _result$[ebp]
	cmp	eax, DWORD PTR _desired_return_code$[ebp]
	jne	SHORT $LN7@TEST_PMC_D
	mov	DWORD PTR tv93[ebp], 1
	jmp	SHORT $LN8@TEST_PMC_D
$LN7@TEST_PMC_D:
	mov	DWORD PTR tv93[ebp], 0
$LN8@TEST_PMC_D:
	mov	ecx, DWORD PTR _result$[ebp]
	push	ecx
	push	OFFSET $SG94511
	call	_FormatTestMesssage
	add	esp, 8
	push	eax
	mov	edx, DWORD PTR tv93[ebp]
	push	edx
	push	2
	mov	eax, DWORD PTR _no$[ebp]
	push	eax
	push	OFFSET $SG94512
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	ecx, DWORD PTR _env$[ebp]
	push	ecx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 48   : 	if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR _desired_return_code$[ebp], 0
	jne	$LN2@TEST_PMC_D

; 49   : 	{
; 50   : 		TEST_Assert(env, FormatTestLabel("PMC_DivRem_I_X (%d.%d)", no, 3), actual_q == desired_q, "商の値が一致しない");

	mov	edx, DWORD PTR _actual_q$[ebp]
	cmp	edx, DWORD PTR _desired_q$[ebp]
	jne	SHORT $LN9@TEST_PMC_D
	mov	DWORD PTR tv136[ebp], 1
	jmp	SHORT $LN10@TEST_PMC_D
$LN9@TEST_PMC_D:
	mov	DWORD PTR tv136[ebp], 0
$LN10@TEST_PMC_D:
	push	OFFSET $SG94514
	mov	eax, DWORD PTR tv136[ebp]
	push	eax
	push	3
	mov	ecx, DWORD PTR _no$[ebp]
	push	ecx
	push	OFFSET $SG94515
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	edx, DWORD PTR _env$[ebp]
	push	edx
	call	_TEST_Assert
	add	esp, 16					; 00000010H

; 51   :         TEST_Assert(env, FormatTestLabel("PMC_DivRem_I_X (%d.%d)", no, 4), actual_r == desired_r, "剰余の値が一致しない");

	mov	eax, DWORD PTR _actual_r$[ebp]
	cmp	eax, DWORD PTR _desired_r$[ebp]
	jne	SHORT $LN11@TEST_PMC_D
	mov	DWORD PTR tv146[ebp], 1
	jmp	SHORT $LN12@TEST_PMC_D
$LN11@TEST_PMC_D:
	mov	DWORD PTR tv146[ebp], 0
$LN12@TEST_PMC_D:
	push	OFFSET $SG94516
	mov	ecx, DWORD PTR tv146[ebp]
	push	ecx
	push	4
	mov	edx, DWORD PTR _no$[ebp]
	push	edx
	push	OFFSET $SG94517
	call	_FormatTestLabel
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _env$[ebp]
	push	eax
	call	_TEST_Assert
	add	esp, 16					; 00000010H
$LN2@TEST_PMC_D:

; 52   :     }
; 53   : 	if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR _v_result$[ebp], 0
	jne	SHORT $LN1@TEST_PMC_D

; 54   : 		ep->PMC_Dispose(v);

	mov	esi, esp
	mov	ecx, DWORD PTR _v$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ep$[ebp]
	mov	eax, DWORD PTR [edx+16]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@TEST_PMC_D:

; 55   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN17@TEST_PMC_D
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	add	esp, 60					; 0000003cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN17@TEST_PMC_D:
	DD	3
	DD	$LN16@TEST_PMC_D
$LN16@TEST_PMC_D:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN13@TEST_PMC_D
	DD	-20					; ffffffecH
	DD	4
	DD	$LN14@TEST_PMC_D
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN15@TEST_PMC_D
$LN15@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	0
$LN14@TEST_PMC_D:
	DB	97					; 00000061H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	0
$LN13@TEST_PMC_D:
	DB	118					; 00000076H
	DB	0
_TEST_PMC_DivRem_I_X ENDP
_TEXT	ENDS
END
